import { test, expect } from '@playwright/test';
const runtimePath='/modules/ssp/releases/v1.9.10/CMMC_L2_SSP_Modern_Editable_v1.9.10.html';
const governedSnapshot=data=>{const copy=structuredClone(data);delete copy.savedAt;return JSON.stringify(copy);};
test('ssp-v1.9.10 UX-3 derives one bounded Needs Attention workspace without contract mutation',async({page})=>{
 const pageErrors=[],consoleErrors=[],externalRequests=[];
 page.on('pageerror',error=>pageErrors.push(String(error)));page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text());});
 page.on('request',request=>{const url=request.url();if(/^https?:/i.test(url)&&!url.startsWith('http://127.0.0.1:4173/'))externalRequests.push(url);});
 await page.goto(runtimePath,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__sspTestHooks&&window.__sspRg1TestHooks&&window.__sspUx3TestHooks);
 expect(await page.evaluate(()=>__sspTestHooks.RELEASE_VERSION)).toBe('1.9.10');expect(await page.evaluate(()=>__sspTestHooks.APP_VERSION)).toBe('1.9.9');expect(await page.evaluate(()=>__sspTestHooks.SCHEMA)).toBe('cmmc-l2-ssp-modern-v1.9.9');expect(await page.locator('.control-card').count()).toBe(110);
 const before=await page.evaluate(()=>__sspTestHooks.collectData(false));await page.locator('#needsAttentionBtn').click();await expect(page.locator('#ux3NeedsAttentionModal')).toBeVisible();await page.waitForFunction(()=>!document.querySelector('#ux3RefreshBtn').disabled);
 const after=await page.evaluate(()=>__sspTestHooks.collectData(false));expect(governedSnapshot(after)).toBe(governedSnapshot(before));expect(after.needsAttentionQueue).toBeUndefined();expect(after.ux3Items).toBeUndefined();
 const ids1=await page.evaluate(()=>__sspUx3TestHooks.getItems().map(item=>item.itemId));const ids2=await page.evaluate(async()=>{await __sspUx3TestHooks.derive();return __sspUx3TestHooks.getItems().map(item=>item.itemId);});expect(ids2).toEqual(ids1);expect(ids1.length).toBeGreaterThan(0);
 await expect(page.locator('#ux3Stats')).toContainText('Visible items');await page.locator('#ux3UrgencyFilter').selectOption('high');expect(await page.locator('.ux3-item').count()).toBeGreaterThan(0);await page.locator('#ux3UrgencyFilter').selectOption('');
 const seeded=await page.evaluate(async()=>{let data=__sspTestHooks.collectData(false);data.reviewGateConfiguration.profileVersion='0.2';__sspTestHooks.applyData(data);const scope={kind:'single-system',portfolioId:'',moduleId:''};const preflight=await __sspRg1TestHooks.rg1BuildRun(scope);const definition=__sspRg1TestHooks.rg2Profile().items.find(item=>item.stageId==='sme-review');data=__sspTestHooks.collectData(false);data.reviewGateRuns=[preflight];data.reviewStageRuns=[{runId:'ux3-stage-test',stageId:'sme-review',state:'corrective-action-required',profileVersion:'0.2',outputProfile:data.reviewGateConfiguration.selectedOutputProfile,scope,sourceIdentity:{appVersion:'1.9.9',schema:'cmmc-l2-ssp-modern-v1.9.9',schemaVersion:'1.9.9',documentVersion:'test',fingerprint:preflight.sourceIdentity.fingerprint},artifactIdentity:{label:'',fingerprint:''},reviewer:{localId:'',displayName:'',role:'SME Technical Reviewer'},startedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),itemResults:[{itemResultId:'ux3-item-test',itemId:definition.itemId,applicable:true,disposition:'corrective-action-required',method:'manual human review',notes:'Needs correction',rationale:'',evidenceRefs:[],affectedRecords:[],correctiveActionRefs:['ux3-ca-test'],updatedAt:new Date().toISOString()}],attestation:{attestationId:'ux3-attest-test',asserted:false,statement:'',assertedAt:''},blockers:['Correction remains open.'],correctiveActionRefs:['ux3-ca-test'],history:[]}];data.reviewCorrectiveActions=[{actionId:'ux3-ca-test',stageRunId:'ux3-stage-test',itemResultId:'ux3-item-test',itemId:definition.itemId,status:'open',owner:{localId:'sme',displayName:'SME'},notes:'Resolve the finding.',evidenceRefs:[],affectedRecords:[],sourceFingerprintOpened:preflight.sourceIdentity.fingerprint,openedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),history:[]}];__sspTestHooks.applyData(data);await __sspUx3TestHooks.refresh();return __sspUx3TestHooks.getItems();});
 expect(seeded.some(item=>item.category==='corrective-actions'&&item.source.collection==='reviewCorrectiveActions')).toBe(true);expect(seeded.some(item=>item.status==='attestation-required')).toBe(true);expect(seeded.some(item=>item.status==='identity-required')).toBe(true);
 await page.keyboard.press('Escape');await expect(page.locator('#ux3NeedsAttentionModal')).toBeHidden();
 expect(pageErrors).toEqual([]);expect(consoleErrors).toEqual([]);expect(externalRequests).toEqual([]);
});
