import { test, expect } from '@playwright/test';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import AxeBuilder from '@axe-core/playwright';
import { stabilizePage } from './module-catalog.mjs';

const RUNTIME='/modules/workshop/releases/v79.1/cmmc_l2_gap_workshop_tool_v79.1.html';
const DIR=path.resolve('modules/workshop/releases/v79.1/tests/fixtures');
const EXACT='builder_v3_10_1_pr113_exact_merge.json';
const MERGE_SHA='efde24c5a0c401c8e1ef9075eb751675359e0dd09419de7a9dae0a34c69c02af';
const PRESERVATION_SHA='2862751b637cf97797e72c74a256f0ba45904f03b7e8076f20a0c67ef2c3fafb';
const read=n=>JSON.parse(fs.readFileSync(path.join(DIR,n),'utf8'));
const text=n=>fs.readFileSync(path.join(DIR,n),'utf8');
const sha=v=>crypto.createHash('sha256').update(v).digest('hex');
const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?`[${v.map(canonical).join(',')}]`:`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;
const fingerprint=v=>sha(canonical(v));
function omitCandidateId(pkg){const x=structuredClone(pkg),e=x.workbook_source.workshop_governance_preservation_v1,row=e.evidence_ownership_records[0];delete row.source_record.candidate_id;delete row.workbook_record.candidate_id;row.source_record_fingerprint=fingerprint(row.source_record);row.workbook_record_fingerprint=fingerprint(row.workbook_record);const body=Object.fromEntries(Object.entries(e).filter(([k])=>k!=='preservation_fingerprint'));e.preservation_fingerprint=fingerprint(body);return x}
function observe(page){const o={external:[],errors:[],console:[]};page.on('request',r=>{const u=r.url();if(/^https?:/i.test(u)&&!u.startsWith('http://127.0.0.1:4173/'))o.external.push(u)});page.on('pageerror',e=>o.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')o.console.push(m.text())});return o}
async function open(page){await page.goto(RUNTIME,{waitUntil:'domcontentloaded'});await stabilizePage(page);await page.evaluate(()=>{window.__v791All=()=>JSON.stringify({actions:state.actionRegister,blockers:state.blockers,ownership:state.evidenceOwnershipV77,sspHandoff:state.sspHandoffGovernanceV70,sspReturn:state.sspReturnGovernanceV71,merge:state.workbookMergeV57})})}
async function seed(page,pkg,candidateMode='source') {await page.evaluate(({pkg,candidateMode})=>{const e=pkg.workbook_source.workshop_governance_preservation_v1;const rows=n=>(e[n]||[]).map(x=>structuredClone(x.source_record));const ownership=rows('evidence_ownership_records');for(const r of ownership){if(candidateMode==='omit')delete r.candidate_id;else if(candidateMode!=='source')r.candidate_id=candidateMode}state.actionRegister={...(state.actionRegister||{}),actions:rows('actions')};state.evidenceOwnershipV77={...(state.evidenceOwnershipV77||{}),accepted_records:ownership.map(record=>structuredClone(record)),candidates:ownership.map(record=>structuredClone(record)),requests:rows('requests'),provider_followups:rows('provider_followups'),history:[],undo_stack:[],redo_stack:[],ui:{current_candidate_id:'',search:'',queue:'all',state:'all',audience:'all'}};state.workbookGovernanceV68={...(state.workbookGovernanceV68||{}),handoff_exports:[{canonical_sha256:e.source_package_identity.canonical_fingerprint,exported_at:'2026-08-01T00:30:00.000Z'}]}},{pkg,candidateMode})}
async function full(page,pkg){return page.evaluate(p=>{p=structuredClone(p);p.practice_results=PRACTICES.map((x,i)=>({Practice_ID:x.id,Implementation_Status:i%2?'Partially Implemented':'Implemented',Gap_Notes:`Gap ${x.id}`,Remediation_POAM_Notes:`Fix ${x.id}`,Reviewer_Notes:i?`Note ${x.id}`:'<script>window.__V791_INJECTED__=1</script>',Source_Sheet:'CMMC Assessment',Source_Row:i+2}));p.objective_results=V54_OBJECTIVES.map((x,i)=>({Practice_ID:v57PracticeId(x.practice_id),Objective_ID:String(x.objective_id).replace(/\s+\[/g,'['),Assessment_Result:i%2?'Met':'Not Met',Evidence_Reviewed:'',Gap_Notes:'',Remediation_POAM_Notes:'',Reviewer_Notes:'',Source_Sheet:'CMMC Assessment',Source_Row:i+2}));p.workbook_source={...(p.workbook_source||{}),practice_rows_detected:110,practices_matched_to_handoff:110,objective_rows_detected:320,sheets:17,formulas:222};return p},pkg)}
async function preview(page,pkg,name){return page.evaluate(({pkg,name})=>{const before=__v791All(),r=v57PreviewMergeText(JSON.stringify(pkg),name);return{blocking:r.blocking,trusted:r.trusted,duplicate:!!r.duplicate,status:r.governance_reconciliation?.status,discrepancies:r.governance_reconciliation?.discrepancies||[],practices:r.practice_results?.length||0,objectives:r.objective_results?.length||0,unchanged:before===__v791All(),operational:__workshopV791TestHooks.operationalSnapshot()}},{pkg,name})}
async function rendered(page){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>setTimeout(resolve,0)))))}
function clean(o){expect(o.external).toEqual([]);expect(o.errors).toEqual([]);expect(o.console).toEqual([])}

test.describe.configure({mode:'serial'});

test('exact PR #113 Merge trusts missing candidate ID and remains non-mutating',async({page},info)=>{test.setTimeout(120000);const seen=observe(page),raw=text(EXACT),pkg=JSON.parse(raw),ext=pkg.workbook_source.workshop_governance_preservation_v1,env=ext.evidence_ownership_records[0];page.on('dialog',d=>d.accept());expect(Buffer.byteLength(raw)).toBe(683940);expect(sha(raw)).toBe(MERGE_SHA);expect(ext.preservation_fingerprint).toBe(PRESERVATION_SHA);expect(ext.record_counts).toEqual({actions:1,evidence_ownership_records:1,requests:0,provider_followups:0});expect(env).toMatchObject({record_id:'candidate-rg4-001',source_record:{ownership_record_id:'candidate-rg4-001',candidate_id:''},workbook_record:{ownership_record_id:'candidate-rg4-001',candidate_id:''}});await open(page);await seed(page,pkg,'omit');expect(await page.evaluate(()=>v791CurrentOwnershipRecords()[0])).toMatchObject({ownership_record_id:'candidate-rg4-001',candidate_id:''});const p=await preview(page,pkg,'pr113-exact.json');expect(p).toMatchObject({blocking:false,trusted:true,duplicate:false,status:'trusted-current',practices:110,objectives:320,unchanged:true});expect(p.discrepancies).toEqual([]);const before=p.operational;await page.evaluate(()=>v57ApplyPendingMerge());await rendered(page);expect(await page.evaluate(()=>__workshopV791TestHooks.operationalSnapshot())).toBe(before);expect(await page.evaluate(()=>state.workbookMergeV57.history[0].governance_reconciliation)).toMatchObject({status:'exact_non_mutating_round_trip',discrepancy_count:0,operational_records_mutated:false});const d=await page.evaluate(raw=>{const before=__v791All(),r=v57PreviewMergeText(raw,'pr113-duplicate.json');return{duplicate:!!r.duplicate,trusted:r.trusted,unchanged:before===__v791All(),operational:__workshopV791TestHooks.operationalSnapshot()}},raw);expect(d).toMatchObject({duplicate:true,trusted:true,unchanged:true,operational:before});await info.attach('exact-pr113-joint.json',{body:Buffer.from(JSON.stringify({builder_head:'bbc8d3bea308a1655567780bea002bc8ef834d8a',builder_runtime_sha256:'2879ee0a933b74c9f27b3c94c0034eafd06f13bc0a8e2d52ba064467b19bfd93',merge_sha256:MERGE_SHA,preservation_fingerprint:PRESERVATION_SHA,preview:p,duplicate:d},null,2)),contentType:'application/json'});clean(seen)});

test('explicit candidate ID matches exactly and ownership ID stays authoritative',async({page},info)=>{const seen=observe(page);await open(page);const pkg=await full(page,read('canonical_nested_extension.json')),env=pkg.workbook_source.workshop_governance_preservation_v1.evidence_ownership_records[0];expect(env).toMatchObject({record_id:'ownership-rg4-001',source_record:{ownership_record_id:'ownership-rg4-001',candidate_id:'candidate-rg4-001'}});const omitted=omitCandidateId(pkg);await seed(page,omitted,'omit');const missing=await preview(page,omitted,'candidate-omitted-all-three.json');expect(missing).toMatchObject({blocking:false,trusted:true,status:'trusted-current',unchanged:true});expect(missing.discrepancies).toEqual([]);await open(page);await seed(page,pkg);const good=await preview(page,pkg,'candidate-exact.json');expect(good).toMatchObject({blocking:false,trusted:true,status:'trusted-current',unchanged:true});for(const value of ['', 'candidate-different-001']){await open(page);await seed(page,pkg,value);const bad=await preview(page,pkg,`candidate-${value||'empty'}.json`);expect(bad).toMatchObject({blocking:true,trusted:false,unchanged:true});expect(bad.discrepancies).toContainEqual(expect.objectContaining({record_type:'evidence_ownership',record_id:'ownership-rg4-001',field:'candidate_id',expected_value:'candidate-rg4-001',observed_value:value,comparison_source:'source_record_vs_current_workshop'}))}await info.attach('candidate-id-results.json',{body:Buffer.from(JSON.stringify({missing,good},null,2)),contentType:'application/json'});clean(seen)});

test('strict negative matrix and package without extension remain governed',async({page},info)=>{const seen=observe(page);await open(page);const base=read('canonical_nested_extension.json');await seed(page,base);const names=['top_level_extension_invalid.json','governed_field_mismatch.json','missing_current_record.json','duplicate_stable_id.json','incorrect_count.json','incorrect_record_fingerprint.json','incorrect_preservation_fingerprint.json','incorrect_source_handoff_linkage.json','malformed_extension.json'];const results=[];for(const name of names){const r=await preview(page,await full(page,read(name)),name);expect(r,name).toMatchObject({blocking:true,trusted:false,unchanged:true});results.push({name,...r})}const raw=text('duplicate_key_extension.json.txt'),dup=await page.evaluate(raw=>{const before=__v791All(),r=v57PreviewMergeText(raw,'duplicate-key.json');return{blocking:r.blocking,trusted:r.trusted,errors:r.validation_errors,unchanged:before===__v791All()}},raw);expect(dup).toMatchObject({blocking:true,trusted:false,unchanged:true});expect(dup.errors.join(' ')).toMatch(/duplicate object key/i);const none=await full(page,read('package_without_extension.json')),supported=await preview(page,none,'without-extension.json');expect(supported).toMatchObject({blocking:false,trusted:true,unchanged:true});const extra=await page.evaluate(pkg=>{const snap=()=>__v791All(),run=(name,fn)=>{const x=structuredClone(pkg);fn(x);const before=snap(),r=v57PreviewMergeText(JSON.stringify(x),name);return{name,blocking:r.blocking,trusted:r.trusted,unchanged:before===snap()}};return[run('unknown-version',x=>x.package_version='2.0'),run('unknown-top',x=>x.workshop_governance_preservation_v1={}),run('duplicate-practice',x=>x.practice_results.push(structuredClone(x.practice_results[0]))),run('duplicate-objective',x=>x.objective_results.push(structuredClone(x.objective_results[0])))]},none);for(const r of extra)expect(r,r.name).toMatchObject({blocking:true,trusted:false,unchanged:true});await info.attach('strict-negative-results.json',{body:Buffer.from(JSON.stringify({results,dup,extra},null,2)),contentType:'application/json'});clean(seen)});

test('runtime UI and axe baseline remain intact',async({page})=>{const seen=observe(page);await page.setViewportSize({width:980,height:720});await open(page);const axe=await new AxeBuilder({page}).analyze();expect(axe.violations.filter(v=>['critical','serious'].includes(v.impact))).toEqual([]);await page.emulateMedia({media:'print'});expect(await page.evaluate(()=>matchMedia('print').matches)).toBe(true);await page.emulateMedia({media:'screen'});await page.evaluate(()=>{document.documentElement.classList.add('dark-mode');document.body.classList.add('dark-mode')});await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement?.tagName||'BODY')).not.toBe('BODY');expect(await page.locator('#v79RegressionWorkspace').count()).toBe(1);expect(await page.locator('#v791IdentityNotice').count()).toBe(1);clean(seen)});
