namespace L2G {
  const WORKSPACE_LABELS: Record<WorkspaceId,string> = { overview:"Overview", "pre-engagement":"Pre-Engagement", evidence:"Evidence", scope:"Scope", "practice-review":"Practice Review", ssp:"SSP", deliverables:"Deliverables", "reviews-actions":"Reviews & Actions" };
  const EVIDENCE_TABS = ["catalog","add","exceptions","duplicates","derived","candidates","relink","imports"] as const;
  type EvidenceTab = typeof EVIDENCE_TABS[number];
  const store = new ProjectStore();
  const sessionLinks = new EvidenceSessionLinks();
  let protection: SessionProtection = {};
  let locked = false;
  let evidenceTab: EvidenceTab = "catalog";
  let evidenceQuery = "";
  let stagedSources: StagedSource[] = [];
  let hashingStatus = "";
  let hashingProgress = 0;
  let hashingController: AbortController | null = null;
  let selectedSourceId = "";
  let relinkTargetId = "";
  let pendingImport: ImportPreview | null = null;
  let toast = "";

  function h(value: unknown): string { return String(value ?? "").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!)); }
  function shortHash(value: string): string { return value ? `${value.slice(0,12)}…${value.slice(-8)}` : "Unhashed"; }
  function bytesLabel(value: number): string { if (!value) return "0 B"; const units=["B","KB","MB","GB"]; const index=Math.min(Math.floor(Math.log(value)/Math.log(1024)),3); return `${(value/1024**index).toFixed(index?1:0)} ${units[index]}`; }
  function dateLabel(value: string): string { const parsed=Date.parse(value); return Number.isFinite(parsed)?new Date(parsed).toLocaleString():value; }
  function setToast(message: string): void { toast=message; render(); window.setTimeout(()=>{if(toast===message){toast="";render();}},3500); }

  function render(): void {
    const root = document.getElementById("app"); if (!root) return;
    if (locked) { root.innerHTML = renderLock(); bindLock(); return; }
    sessionLinks.bindProject(store.document.manifest.project_id);
    const state=store.document.state;
    root.innerHTML = `<div class="shell">
      <header class="topbar">
        <button id="rail-toggle" aria-label="Toggle workspace navigation">☰</button>
        <span class="brand">L2G Integrated Suite</span><span class="release-badge">v${h(window.__L2G_RELEASE__.version)} · Evidence Catalog Core</span>
        <button id="new-project">New</button><button id="open-project">Open</button><button id="save-project" class="primary">Save encrypted</button>
        <button id="undo" ${store.canUndo?"":"disabled"}>Undo</button><button id="redo" ${store.canRedo?"":"disabled"}>Redo</button>
        <span class="spacer"></span>
        <label for="profile-select" class="sr-only">Presentation profile</label><select id="profile-select"><option value="advisor" ${state.profile==="advisor"?"selected":""}>Advisor View</option><option value="client" ${state.profile==="client"?"selected":""}>Client View</option><option value="reviewer" ${state.profile==="reviewer"?"selected":""}>Reviewer View</option></select>
        <button id="lock-project">Lock</button>
      </header>
      <div class="layout ${state.rail_collapsed?"rail-collapsed":""}">
        <aside class="rail ${state.rail_collapsed?"collapsed":""}"><nav aria-label="Workspaces">${Object.entries(WORKSPACE_LABELS).map(([id,label])=>`<button data-workspace="${id}" ${state.active_workspace===id?'aria-current="page"':""}><span aria-hidden="true">${workspaceIcon(id as WorkspaceId)}</span><span class="nav-label">${h(label)}</span></button>`).join("")}</nav><p class="qualification">Synthetic-only. Presentation profiles are not security roles. Evidence records, hashes, and relationships do not determine authenticity, sufficiency, readiness, compliance, risk, certification, scoring, or Met/Not Met.</p></aside>
        <main id="workspace" tabindex="-1">${store.migrationNotice?`<div class="notice warning" role="status">${h(store.migrationNotice)}</div>`:""}${toast?`<div class="notice ok" role="status">${h(toast)}</div>`:""}${renderWorkspace()}</main>
      </div>
      ${renderInspector()}
    </div>`;
    bindShell(); bindWorkspace();
  }

  function workspaceIcon(id: WorkspaceId): string { return ({overview:"◫","pre-engagement":"◷",evidence:"▣",scope:"◇","practice-review":"✓",ssp:"§",deliverables:"▤","reviews-actions":"↻"} as Record<WorkspaceId,string>)[id]; }
  function renderWorkspace(): string {
    const id=store.document.state.active_workspace;
    if(id==="evidence")return renderEvidenceWorkspace();
    if(id==="overview")return renderOverview();
    if(id==="reviews-actions")return renderReviews();
    return renderContextWorkspace(id);
  }

  function renderOverview(): string {
    const state=store.document.state; const ep=buildEvidenceProjection(state.evidence,"overview",state.profile); const gp=buildEngagementProjection(state.engagement,"overview",state.profile);
    const exceptions=ep.next_work.filter(item=>item.kind==="exception"||item.kind==="missing-source").length;
    const pending=ep.next_work.filter(item=>item.kind==="candidate-mapping"||item.kind==="import-review").length;
    return `<section aria-labelledby="workspace-title"><div class="workspace-header"><div><h1 id="workspace-title">Engagement overview</h1><p>One governed engagement context with reference-only Evidence. Counts and next work are calculated from the active presentation profile only.</p></div></div>
      <div class="metrics"><div class="metric"><strong>${ep.sources.length}</strong><span>visible Evidence sources</span></div><div class="metric"><strong>${ep.derived_records.length}</strong><span>visible derived records</span></div><div class="metric"><strong>${exceptions}</strong><span>visible source exceptions</span></div><div class="metric"><strong>${pending}</strong><span>visible proposals/import reviews</span></div></div>
      <div class="grid" style="margin-top:.8rem"><article class="card"><h2>${h(gp.identity.engagement_name)}</h2><p>${h(gp.identity.delivery_context)}</p><p class="meta">${h(gp.identity.phase)} · ${h(gp.identity.target_level)} · ${h(gp.identity.information_label)}</p></article>
      <article class="card"><h2>Evidence next work</h2><div class="list">${ep.next_work.map(item=>`<div><strong>${h(item.title)}</strong><p>${h(item.detail)}</p></div>`).join("")}</div></article>
      <article class="card"><h2>Engagement next work</h2><div class="list">${gp.next_work.map(item=>`<div><strong>${h(item.title)}</strong><p>${h(item.detail)}</p></div>`).join("")}</div></article></div>
      <div class="notice">A SHA-256 match establishes byte equality only. It does not establish authenticity, relevance, currency, implementation, or evidence sufficiency.</div></section>`;
  }

  function renderContextWorkspace(id: WorkspaceId): string {
    const state=store.document.state; const ep=buildEvidenceProjection(state.evidence,id,state.profile); const gp=buildEngagementProjection(state.engagement,id,state.profile);
    return `<section aria-labelledby="workspace-title"><div class="workspace-header"><div><h1 id="workspace-title">${h(WORKSPACE_LABELS[id])}</h1><p>This v0.4 workspace consumes frozen Engagement and Evidence projections. Its substantive domain authority has not migrated yet.</p></div></div>
      <div class="grid"><article class="card"><h2>Engagement context</h2><p><strong>${h(gp.identity.system_name)}</strong></p><p>${h(gp.identity.objectives)}</p><p class="meta">Source domain: Engagement · read-only projection</p></article>
      <article class="card"><h2>Evidence context</h2><p><strong>${ep.sources.length}</strong> visible source references and <strong>${ep.derived_records.length}</strong> visible bounded derived records.</p><p class="meta">Source domain: Evidence · read-only frozen projection</p></article>
      <article class="card"><h2>Authority boundary</h2><p>Evidence may create reviewable proposals, but it cannot silently change ${h(WORKSPACE_LABELS[id])} authority or create readiness, compliance, evidence-sufficiency, risk, scoring, certification, or Met/Not Met conclusions.</p></article></div></section>`;
  }

  function renderReviews(): string {
    const state=store.document.state; const gp=buildEngagementProjection(state.engagement,"reviews-actions",state.profile); const ep=buildEvidenceProjection(state.evidence,"reviews-actions",state.profile);
    return `<section aria-labelledby="workspace-title"><div class="workspace-header"><div><h1 id="workspace-title">Reviews & Actions</h1><p>Review candidate proposals and factual work-management items without transferring domain authority.</p></div></div>
      ${state.profile!=="client"?`<div class="grid">${gp.candidates.map(candidate=>`<article class="card"><h2>Engagement candidate</h2><p>${h(candidate.source_kind)} → ${h(candidate.target_type)}</p><p>${h(candidate.rationale)}</p><pre class="mono">${h(JSON.stringify(candidate.proposed_fields,null,2))}</pre>${state.profile==="advisor"&&candidate.state==="candidate"?`<div class="card-actions"><button data-accept-engagement="${h(candidate.candidate_id)}" class="primary">Accept identity candidate</button><button data-reject-engagement="${h(candidate.candidate_id)}">Reject</button></div>`:""}<p class="meta">State: ${h(candidate.state)}</p></article>`).join("")}${ep.candidate_mappings.map(mapping=>renderCandidateCard(mapping)).join("")}</div>`:`<div class="empty">No review candidates are approved for this presentation.</div>`}
      <h2>Command history</h2><div class="history">${store.document.history.slice(-20).reverse().map(event=>`<article><strong>${h(event.action)}</strong><div>${h(event.summary)}</div><small>${h(dateLabel(event.timestamp))} · ${h(event.profile)}</small></article>`).join("")}</div></section>`;
  }

  function renderEvidenceWorkspace(): string {
    const state=store.document.state; const projection=buildEvidenceProjection(state.evidence,"evidence",state.profile); const exceptions=projection.next_work.filter(item=>item.kind!=="informational").length;
    return `<section aria-labelledby="workspace-title"><div class="workspace-header"><div><h1 id="workspace-title">Evidence</h1><p>Register, verify, relink, review, and map reference-only source records. Original files remain outside the encrypted project.</p></div><div class="workspace-actions">${state.profile==="advisor"?`<button id="add-evidence" class="primary">Add Evidence</button><button id="relink-evidence">Relink Evidence</button><button id="import-package">Import Package</button>`:""}<span class="badge">${exceptions} factual attention item${exceptions===1?"":"s"}</span></div></div>
      <div class="notice">Original files stay outside the project. The app records bounded metadata, SHA-256 fingerprints, source locations, summaries, provenance, and proposals only. Hashes prove byte equality—not trust or sufficiency.</div>
      <div class="tablist" role="tablist" aria-label="Evidence views">${EVIDENCE_TABS.map(tab=>`<button role="tab" data-evidence-tab="${tab}" aria-selected="${evidenceTab===tab}" ${state.profile==="client"&&!(["catalog","derived"] as string[]).includes(tab)?"hidden":""}>${h(tabLabel(tab))}</button>`).join("")}</div>
      <div class="toolbar"><label for="evidence-search" class="sr-only">Search visible Evidence</label><input id="evidence-search" type="search" value="${h(evidenceQuery)}" placeholder="Search visible Evidence metadata and approved derived content"><button id="clear-search">Clear</button><span class="badge">${projection.sources.length} visible source${projection.sources.length===1?"":"s"}</span></div>
      ${renderSearch(projection)}${renderEvidenceTab(projection)}</section>`;
  }

  function tabLabel(tab: EvidenceTab): string { return ({catalog:"Catalog",add:"Add Evidence",exceptions:"Exception & Trust Queue",duplicates:"Duplicates & Revisions",derived:"Derived Records",candidates:"Candidate Mappings",relink:"Relink Evidence",imports:"Import Packages"} as Record<EvidenceTab,string>)[tab]; }
  function renderSearch(projection: EvidenceProjection): string {
    if(!evidenceQuery.trim())return ""; const results=searchEvidenceProjection(projection,evidenceQuery);
    if(!results.length)return `<div class="empty">${projection.profile==="client"?"No approved evidence references match this search.":"No visible Evidence records match this search."}</div>`;
    return `<div class="search-results" aria-label="Evidence search results">${results.map(result=>`<button class="search-result" data-inspect-ref="${h(result.id)}"><strong>${h(result.kind)}: ${h(result.title)}</strong><br><span class="muted">${h(result.detail)}</span></button>`).join("")}</div>`;
  }
  function renderEvidenceTab(projection: EvidenceProjection): string {
    if(evidenceTab==="catalog")return renderCatalog(projection);
    if(evidenceTab==="add")return renderAdd();
    if(evidenceTab==="exceptions")return renderExceptions(projection);
    if(evidenceTab==="duplicates")return renderDuplicates(projection);
    if(evidenceTab==="derived")return renderDerived(projection);
    if(evidenceTab==="candidates")return renderCandidates(projection);
    if(evidenceTab==="relink")return renderRelink(projection);
    return renderImports(projection);
  }

  function renderCatalog(projection: EvidenceProjection): string {
    if(!projection.sources.length)return `<div class="empty">${projection.profile==="client"?"No evidence references are approved for this presentation.":"No evidence references have been registered. Add synthetic files or import a recognized synthetic DocConverter package."}</div>`;
    const client=projection.profile==="client";
    return `<div class="table-wrap"><table><thead><tr><th>Source</th><th>Type</th>${client?"":"<th>Fingerprint</th><th>Processing</th><th>Trust</th><th>Session</th>"}<th>Review</th><th>Actions</th></tr></thead><tbody>${projection.sources.map(raw=>{const source=raw as EvidenceSourceRecord|ClientEvidenceSource;const title=client?(source as ClientEvidenceSource).client_label:(source as EvidenceSourceRecord).display_label;const full=raw as EvidenceSourceRecord;return `<tr><td data-label="Source"><strong>${h(title)}</strong>${client?"":`<div class="meta">${h(full.original_name)} · ${h(bytesLabel(full.size_bytes))}</div>`}</td><td data-label="Type">${h(source.media_type)}</td>${client?"":`<td data-label="Fingerprint" class="fingerprint">${h(shortHash(full.fingerprint?.sha256??""))}</td><td data-label="Processing"><span class="status">${h(full.processing_state)}</span></td><td data-label="Trust"><span class="status ${full.trust_state==="exception-open"||full.trust_state==="rejected"?"attention":""}">${h(full.trust_state)}</span></td><td data-label="Session"><span class="status">${h(sessionLinks.getState(full.evidence_id))}</span></td>`}<td data-label="Review"><span class="status">${h(source.review_state)}</span></td><td data-label="Actions"><div class="card-actions"><button data-inspect-ref="${h(source.evidence_id)}">Inspect</button>${!client&&store.document.state.profile==="advisor"?`<button data-relink-source="${h(source.evidence_id)}">Relink</button><button data-source-candidate="${h(source.evidence_id)}">Create candidate</button><button data-archive-source="${h(source.evidence_id)}">Archive</button>`:""}</div></td></tr>`}).join("")}</tbody></table></div>`;
  }

  function renderAdd(): string {
    if(store.document.state.profile!=="advisor")return `<div class="empty">Source registration is available in Advisor View.</div>`;
    if(!stagedSources.length&&!hashingStatus)return `<div class="empty"><h2>No staged sources</h2><p>Select synthetic files to hash locally. No original bytes are stored in the project.</p><button id="choose-evidence-files" class="primary">Choose files</button></div>`;
    return `<div class="list">${hashingStatus?`<div class="card" role="status"><strong>${h(hashingStatus)}</strong><div class="progress" aria-label="Hashing progress"><span style="width:${Math.round(hashingProgress*100)}%"></span></div><div class="card-actions"><button id="cancel-hashing" class="danger">Cancel hashing</button></div></div>`:""}${stagedSources.map(item=>`<article class="card" data-staged-card="${h(item.staging_id)}"><h2>${h(item.original_name)}</h2><p class="fingerprint">${h(item.sha256)}</p>${item.duplicate_source_refs.length?`<div class="notice warning">Exact bytes already exist in ${item.duplicate_source_refs.length} registered source reference${item.duplicate_source_refs.length===1?"":"s"}. Registration will create an explicit separate duplicate reference.</div>`:""}<div class="grid"><div class="field"><label>Display label<input data-staged-field="display_label" value="${h(item.display_label)}"></label></div><div class="field"><label>Client label<input data-staged-field="client_label" value="${h(item.client_label)}"></label></div><div class="field"><label>Collection label<input data-staged-field="collection_label" value="${h(item.collection_label)}"></label></div><div class="field"><label>Visibility<select data-staged-field="visibility"><option value="advisor-only" ${item.visibility==="advisor-only"?"selected":""}>Advisor-only</option><option value="client-safe" ${item.visibility==="client-safe"?"selected":""}>Client-safe</option><option value="approved-for-client-presentation" ${item.visibility==="approved-for-client-presentation"?"selected":""}>Approved for client presentation</option></select></label></div><div class="field"><label>Tags, comma separated<input data-staged-field="tags" value="${h(item.tags.join(", "))}"></label></div></div><div class="card-actions"><button data-remove-staged="${h(item.staging_id)}">Remove staged item</button></div></article>`).join("")}<div class="card-actions"><button id="choose-evidence-files">Add more files</button><button id="commit-staged" class="primary" ${stagedSources.length?"":"disabled"}>Commit staged sources</button><button id="discard-staged">Discard staging</button></div></div>`;
  }

  function renderExceptions(projection: EvidenceProjection): string {
    if(projection.profile==="client")return `<div class="empty">Exception and trust details are not included in Client View.</div>`;
    const items=projection.next_work.filter(item=>item.kind!=="informational"); if(!items.length)return `<div class="empty">No visible Evidence exception or work-management item is open.</div>`;
    return `<div class="grid">${items.map(item=>`<article class="card"><h2>${h(item.title)}</h2><p>${h(item.detail)}</p><p class="meta">${h(item.kind)} · priority ${item.priority}</p><div class="card-actions"><button data-inspect-ref="${h(item.record_ref)}">Inspect related record</button></div></article>`).join("")}</div>`;
  }

  function renderDuplicates(projection: EvidenceProjection): string {
    if(projection.profile==="client")return `<div class="empty">Duplicate and revision details are not included in Client View.</div>`;
    if(!projection.duplicate_groups.length)return `<div class="empty">No exact duplicate groups are registered.</div>`;
    return `<div class="list"><div class="notice">Exact duplicates contain the same bytes. The app does not decide which business reference should be retained.</div>${projection.duplicate_groups.map(group=>`<article class="card"><h2>Exact duplicate group</h2><p class="fingerprint">${h(group.sha256)}</p><p>State: <span class="status ${group.state==="unresolved"?"attention":"success"}">${h(group.state)}</span></p><div class="list">${group.members.map(member=>{const source=store.document.state.evidence.sources.find(item=>item.evidence_id===member.source_ref);return `<div><strong>${h(source?.display_label??member.source_ref)}</strong> — ${h(member.disposition)}<br><span class="muted">${h(member.rationale)}</span></div>`}).join("")}</div>${store.document.state.profile==="advisor"?`<div class="field"><label>Disposition rationale<textarea data-duplicate-rationale="${h(group.duplicate_group_id)}">Select one primary and retain the other exact byte references as duplicates.</textarea></label></div><div class="card-actions"><button data-resolve-duplicate="${h(group.duplicate_group_id)}" class="primary">Resolve: first primary, others duplicate</button></div>`:""}</article>`).join("")}</div>`;
  }

  function renderDerived(projection: EvidenceProjection): string {
    if(!projection.derived_records.length)return `<div class="empty">No visible bounded derived records are available.</div>`;
    return `<div class="grid">${projection.derived_records.map(item=>`<article class="card"><h2>${h(item.title)}</h2><span class="badge">${h(item.kind)}</span><p>${h(item.summary)}</p>${item.fields.length?`<dl>${item.fields.map(field=>`<dt>${h(field.name)}</dt><dd>${h(field.value)}</dd>`).join("")}</dl>`:""}<p class="meta">Review: ${h(item.review_state)} · Source-derived; no sufficiency conclusion.</p><div class="card-actions"><button data-inspect-ref="${h(item.derived_id)}">Inspect traceability</button></div></article>`).join("")}</div>`;
  }
  function renderCandidates(projection: EvidenceProjection): string { if(projection.profile==="client")return `<div class="empty">Candidate mappings are not included in Client View.</div>`; if(!projection.candidate_mappings.length)return `<div class="empty">No Evidence candidate mappings are queued.</div>`; return `<div class="grid">${projection.candidate_mappings.map(renderCandidateCard).join("")}</div>`; }
  function renderCandidateCard(mapping: EvidenceCandidateMapping): string { return `<article class="card"><h2>${h(mapping.target_domain)} · ${h(mapping.target_type)}</h2><p>${h(mapping.rationale)}</p><pre class="mono">${h(JSON.stringify(Object.fromEntries(mapping.proposed_fields.map(field=>[field.name,field.value])),null,2))}</pre><p class="meta">State: ${h(mapping.state)}${mapping.target_candidate_ref?` · Target ${h(mapping.target_candidate_ref)}`:""}</p>${store.document.state.profile==="advisor"&&mapping.state==="awaiting-review"?`<div class="card-actions"><button data-publish-candidate="${h(mapping.candidate_id)}" class="primary" ${mapping.target_domain!=="engagement"?"disabled":""}>${mapping.target_domain==="engagement"?"Publish to Engagement candidate":"Target workspace not yet implemented"}</button></div>`:""}</article>`; }

  function renderRelink(projection: EvidenceProjection): string {
    if(projection.profile!=="advisor")return `<div class="empty">Relink is available in Advisor View.</div>`;
    if(!projection.sources.length)return `<div class="empty">No sources are available to relink.</div>`;
    return `<div class="list"><div class="notice">Relinking is session-only. The app rehashes selected bytes; filename, size, type, and modified time are hints only.</div>${projection.sources.map(raw=>{const source=raw as EvidenceSourceRecord;return `<article class="card"><h2>${h(source.display_label)}</h2><p>${h(source.original_name)}</p><p class="fingerprint">${h(source.fingerprint?.sha256??"Unhashed external reference")}</p><p>Session: <span class="status">${h(sessionLinks.getState(source.evidence_id))}</span></p><div class="card-actions"><button data-relink-source="${h(source.evidence_id)}" ${source.fingerprint?"":"disabled"}>Select exact file</button>${sessionLinks.getState(source.evidence_id)!=="unlinked"?`<button data-unlink-source="${h(source.evidence_id)}">Clear session link</button>`:""}</div></article>`}).join("")}</div>`;
  }

  function renderImports(projection: EvidenceProjection): string {
    if(projection.profile!=="advisor")return `<div class="empty">Package import is available in Advisor View.</div>`;
    return `<div class="list"><div class="notice">Recognized stable packages are previewed as low-authority Evidence records. Applying a preview does not accept Scope, Practice Review, SSP, responsibility, sufficiency, or client approval.</div>${pendingImport?`<article class="card"><h2>${h(pendingImport.package_kind)} ${h(pendingImport.package_version)}</h2><p>${h(pendingImport.package_name)} · ${h(bytesLabel(pendingImport.package_size_bytes))}</p><div class="metrics"><div class="metric"><strong>${pendingImport.sources.length}</strong><span>staged sources</span></div><div class="metric"><strong>${pendingImport.derived_records.length}</strong><span>staged derived records</span></div><div class="metric"><strong>${pendingImport.candidates.length}</strong><span>staged proposals</span></div><div class="metric"><strong>${pendingImport.rejected.length}</strong><span>rejected rows</span></div></div>${pendingImport.warnings.length||pendingImport.rejected.length?`<div class="notice warning">${[...pendingImport.warnings,...pendingImport.rejected].map(item=>`<div>${h(item)}</div>`).join("")}</div>`:""}<div class="card-actions"><button id="apply-import" class="primary">Apply reviewed valid set atomically</button><button id="reject-import">Reject preview</button></div></article>`:`<div class="empty"><h2>No package preview</h2><button id="choose-package" class="primary">Choose recognized JSON package</button></div>`}${projection.import_receipts.map(receipt=>`<article class="card"><h2>${h(receipt.package_kind)}</h2><p>${h(receipt.package_name)}</p><p class="meta">${h(receipt.state)} · ${h(dateLabel(receipt.imported_at))} · ${receipt.staged_source_refs.length} source references</p></article>`).join("")}</div>`;
  }

  function renderInspector(): string {
    if(!store.document.state.inspector_open||!selectedSourceId)return ""; const evidence=store.document.state.evidence;
    const source=evidence.sources.find(item=>item.evidence_id===selectedSourceId); const location=evidence.locations.find(item=>item.location_id===selectedSourceId); const derived=evidence.derived_records.find(item=>item.derived_id===selectedSourceId); const candidate=evidence.candidate_mappings.find(item=>item.candidate_id===selectedSourceId);
    if(store.document.state.profile==="client"){
      const projection=buildEvidenceProjection(evidence,"evidence","client"); const visible=projection.sources.find(item=>item.evidence_id===selectedSourceId) as ClientEvidenceSource|undefined;
      if(!visible)return ""; return `<aside class="inspector" role="dialog" aria-modal="false" aria-labelledby="inspector-title"><div class="inspector-header"><div><h2 id="inspector-title">${h(visible.client_label)}</h2><p class="muted">Approved presentation detail</p></div><button id="close-inspector" aria-label="Close inspector">×</button></div><dl><dt>Type</dt><dd>${h(visible.media_type)}</dd><dt>Lifecycle</dt><dd>${h(visible.lifecycle)}</dd><dt>Review</dt><dd>${h(visible.review_state)}</dd><dt>Tags</dt><dd>${h(visible.tags.join(", "))}</dd></dl></aside>`;
    }
    const item=source??location??derived??candidate; if(!item)return "";
    return `<aside class="inspector" role="dialog" aria-modal="false" aria-labelledby="inspector-title"><div class="inspector-header"><div><h2 id="inspector-title">Evidence inspector</h2><p class="muted">Advisor/Reviewer source traceability</p></div><button id="close-inspector" aria-label="Close inspector">×</button></div><pre class="mono">${h(JSON.stringify(item,null,2))}</pre></aside>`;
  }

  function renderLock(): string { return `<div class="lock-screen"><section class="lock-card"><h1>L2G project locked</h1><p>Encrypted browser recovery is available only with the project passphrase. Session file associations were cleared.</p><div class="field"><label for="unlock-passphrase">Passphrase</label><input id="unlock-passphrase" type="password" autocomplete="current-password"></div><button id="unlock-project" class="primary">Unlock recovery</button><p id="unlock-error" class="danger-text" role="alert"></p></section></div>`; }

  function bindShell(): void {
    document.getElementById("rail-toggle")?.addEventListener("click",()=>{store.document.state.rail_collapsed=!store.document.state.rail_collapsed;render();});
    document.querySelectorAll<HTMLButtonElement>("[data-workspace]").forEach(button=>button.addEventListener("click",()=>{store.document.state.active_workspace=button.dataset.workspace as WorkspaceId;store.document.state.inspector_open=false;selectedSourceId="";render();document.getElementById("workspace")?.focus();}));
    document.getElementById("new-project")?.addEventListener("click",()=>void newProject()); document.getElementById("open-project")?.addEventListener("click",()=>document.getElementById("project-open-input")?.click()); document.getElementById("save-project")?.addEventListener("click",()=>void saveProject());
    document.getElementById("undo")?.addEventListener("click",()=>{store.undo();void persistRecovery();}); document.getElementById("redo")?.addEventListener("click",()=>{store.redo();void persistRecovery();});
    document.getElementById("lock-project")?.addEventListener("click",()=>void lockProject());
    document.getElementById("profile-select")?.addEventListener("change",event=>{store.document.state.profile=(event.target as HTMLSelectElement).value as PresentationProfile;store.document.state.inspector_open=false;selectedSourceId="";evidenceQuery="";if(store.document.state.profile==="client"&&!(["catalog","derived"] as EvidenceTab[]).includes(evidenceTab))evidenceTab="catalog";render();});
  }

  function bindWorkspace(): void {
    document.querySelectorAll<HTMLButtonElement>("[data-evidence-tab]").forEach(button=>button.addEventListener("click",()=>{evidenceTab=button.dataset.evidenceTab as EvidenceTab;render();}));
    document.getElementById("add-evidence")?.addEventListener("click",()=>{evidenceTab="add";render();document.getElementById("evidence-add-input")?.click();}); document.getElementById("choose-evidence-files")?.addEventListener("click",()=>document.getElementById("evidence-add-input")?.click());
    document.getElementById("relink-evidence")?.addEventListener("click",()=>{evidenceTab="relink";render();}); document.getElementById("import-package")?.addEventListener("click",()=>{evidenceTab="imports";render();document.getElementById("package-import-input")?.click();}); document.getElementById("choose-package")?.addEventListener("click",()=>document.getElementById("package-import-input")?.click());
    const search=document.getElementById("evidence-search") as HTMLInputElement|null; search?.addEventListener("input",()=>{evidenceQuery=search.value;render();const next=document.getElementById("evidence-search") as HTMLInputElement|null;next?.focus();next?.setSelectionRange(evidenceQuery.length,evidenceQuery.length);}); document.getElementById("clear-search")?.addEventListener("click",()=>{evidenceQuery="";render();});
    document.querySelectorAll<HTMLButtonElement>("[data-inspect-ref]").forEach(button=>button.addEventListener("click",()=>{selectedSourceId=button.dataset.inspectRef??"";store.document.state.inspector_open=true;render();})); document.getElementById("close-inspector")?.addEventListener("click",()=>{store.document.state.inspector_open=false;selectedSourceId="";render();});
    document.querySelectorAll<HTMLInputElement|HTMLSelectElement>("[data-staged-field]").forEach(input=>input.addEventListener("change",()=>{const card=input.closest<HTMLElement>("[data-staged-card]");const item=stagedSources.find(source=>source.staging_id===card?.dataset.stagedCard);if(!item)return;const field=input.dataset.stagedField!;if(field==="tags")item.tags=input.value.split(",").map(value=>value.trim()).filter(Boolean);else if(field==="visibility")item.visibility=input.value as Visibility;else (item as unknown as Record<string,unknown>)[field]=input.value;}));
    document.querySelectorAll<HTMLButtonElement>("[data-remove-staged]").forEach(button=>button.addEventListener("click",()=>{stagedSources=stagedSources.filter(item=>item.staging_id!==button.dataset.removeStaged);render();})); document.getElementById("discard-staged")?.addEventListener("click",()=>{stagedSources=[];hashingController?.abort();render();}); document.getElementById("cancel-hashing")?.addEventListener("click",()=>hashingController?.abort()); document.getElementById("commit-staged")?.addEventListener("click",()=>commitStaged());
    document.querySelectorAll<HTMLButtonElement>("[data-relink-source]").forEach(button=>button.addEventListener("click",()=>{relinkTargetId=button.dataset.relinkSource??"";document.getElementById("evidence-relink-input")?.click();})); document.querySelectorAll<HTMLButtonElement>("[data-unlink-source]").forEach(button=>button.addEventListener("click",()=>{sessionLinks.unlink(button.dataset.unlinkSource??"");render();}));
    document.querySelectorAll<HTMLButtonElement>("[data-archive-source]").forEach(button=>button.addEventListener("click",()=>archiveSource(button.dataset.archiveSource??""))); document.querySelectorAll<HTMLButtonElement>("[data-source-candidate]").forEach(button=>button.addEventListener("click",()=>void createCandidateForSource(button.dataset.sourceCandidate??"")));
    document.querySelectorAll<HTMLButtonElement>("[data-resolve-duplicate]").forEach(button=>button.addEventListener("click",()=>resolveDuplicate(button.dataset.resolveDuplicate??""))); document.querySelectorAll<HTMLButtonElement>("[data-publish-candidate]").forEach(button=>button.addEventListener("click",()=>publishCandidate(button.dataset.publishCandidate??"")));
    document.getElementById("apply-import")?.addEventListener("click",()=>applyPendingImport()); document.getElementById("reject-import")?.addEventListener("click",()=>{pendingImport=null;setToast("Package preview rejected. No Evidence records changed.");});
    document.querySelectorAll<HTMLButtonElement>("[data-accept-engagement]").forEach(button=>button.addEventListener("click",()=>decideEngagement(button.dataset.acceptEngagement??"","accept"))); document.querySelectorAll<HTMLButtonElement>("[data-reject-engagement]").forEach(button=>button.addEventListener("click",()=>decideEngagement(button.dataset.rejectEngagement??"","reject")));
  }

  function bindLock(): void { document.getElementById("unlock-project")?.addEventListener("click",()=>void unlockProject()); }

  async function newProject(): Promise<void> { if(!window.confirm("Create a new synthetic project? Unsaved in-memory changes will be discarded."))return; clearSessionProtection(protection); protection={};sessionLinks.clear();store.reset();locked=false;stagedSources=[];pendingImport=null;evidenceQuery="";evidenceTab="catalog";await clearRecovery();render(); }
  async function saveProject(): Promise<void> {
    try { if(!protection.baseKey){const values=await promptFields("Protect project",[{name:"passphrase",label:"Passphrase",type:"password"},{name:"confirm",label:"Confirm passphrase",type:"password"}]);if(!values)return;if(promptValue(values,"passphrase")!==promptValue(values,"confirm"))throw new Error("Passphrases do not match.");protection=await deriveProjectKeys(promptValue(values,"passphrase"));} const bytes=await encryptProjectDocument(store.document,protection,"portable-project");await downloadBytes(bytes,window.__L2G_RELEASE__.artifact_name.replace(/\.html$/,"")+".l2g","application/octet-stream");await saveRecovery(store.document,protection);setToast("Encrypted v0.4 project download created and recovery updated."); }
    catch(error){await showMessage("Save failed",errorMessage(error),true);}
  }
  async function lockProject(): Promise<void> { try { if(!protection.baseKey){const values=await promptFields("Set passphrase before locking",[{name:"passphrase",label:"Passphrase",type:"password"},{name:"confirm",label:"Confirm passphrase",type:"password"}]);if(!values)return;if(promptValue(values,"passphrase")!==promptValue(values,"confirm"))throw new Error("Passphrases do not match.");protection=await deriveProjectKeys(promptValue(values,"passphrase"));}await saveRecovery(store.document,protection);clearSessionProtection(protection);protection={};sessionLinks.clear();locked=true;render();}catch(error){await showMessage("Lock failed",errorMessage(error),true);} }
  async function unlockProject(): Promise<void> { const input=document.getElementById("unlock-passphrase") as HTMLInputElement|null;const error=document.getElementById("unlock-error");try{if(!input?.value)throw new Error("Enter the project passphrase.");const next=await deriveProjectKeys(input.value);const recovered=await restoreRecovery(next);if(!recovered)throw new Error("No encrypted recovery record is available.");protection=next;store.replace(recovered,false);locked=false;sessionLinks.bindProject(recovered.manifest.project_id);render();}catch(reason){if(error)error.textContent=errorMessage(reason);} }
  async function persistRecovery(): Promise<void> { if(protection.baseKey)try{await saveRecovery(store.document,protection);}catch{/* bounded best effort; explicit save reports errors */} }

  async function handleProjectOpen(file: File): Promise<void> {
    try { const values=await promptFields("Unlock project",[{name:"passphrase",label:"Passphrase",type:"password"}]);if(!values)return;const next=await deriveProjectKeys(promptValue(values,"passphrase"));const bytes=new Uint8Array(await file.arrayBuffer());const result=await decryptProjectBytes(bytes,next,"portable-project",true);protection=next;sessionLinks.clear();store.replace(result.document,result.legacy);locked=false;await saveRecovery(store.document,protection);setToast(result.legacy?"Project migrated to v0.4. Save a new encrypted file.":"Encrypted v0.4 project opened.");}catch(error){await showMessage("Open failed",errorMessage(error),true);}finally{const input=document.getElementById("project-open-input") as HTMLInputElement|null;if(input)input.value="";}
  }

  async function handleEvidenceFiles(files: FileList): Promise<void> {
    if(files.length>500){await showMessage("Selection rejected","A source batch may contain at most 500 files.",true);return;} evidenceTab="add";hashingController=new AbortController();
    try{for(let index=0;index<files.length;index++){const file=files.item(index)!;hashingStatus=`Hashing ${index+1} of ${files.length}: ${sanitizeEvidenceFilename(file.name)}`;hashingProgress=0;render();const digest=await hashEvidenceFile(file,(completed,total)=>{hashingProgress=total?completed/total:1;const status=document.querySelector<HTMLElement>(".progress>span");if(status)status.style.width=`${Math.round(hashingProgress*100)}%`;},hashingController.signal);stagedSources.push(createStagedSource(file,digest,store.document.state.evidence));}hashingStatus="";hashingProgress=0;render();}
    catch(error){hashingStatus="";hashingProgress=0;if((error as Error).name!=="AbortError")await showMessage("Hashing failed",errorMessage(error),true);else setToast("Hashing was cancelled. No Evidence record was changed.");render();}finally{hashingController=null;const input=document.getElementById("evidence-add-input") as HTMLInputElement|null;if(input)input.value="";}
  }
  function commitStaged(): void { try{let created:EvidenceSourceRecord[]=[];store.execute("evidence.register-sources","evidence",store.document.state.evidence.catalog_id,`Registered ${stagedSources.length} locally hashed source reference${stagedSources.length===1?"":"s"}.`,document=>{created=registerStagedSources(document.state.evidence,stagedSources,document.state.profile);},"Registered Evidence source batch");created.forEach((source,index)=>{const staged=stagedSources[index];if(staged)sessionLinks.setExact(source.evidence_id,staged.file);});stagedSources=[];evidenceTab="catalog";void persistRecovery();setToast("Evidence source references registered. Original bytes remain outside the project.");}catch(error){void showMessage("Registration failed",errorMessage(error),true);} }

  async function handleRelinkFile(file: File): Promise<void> {
    const source=store.document.state.evidence.sources.find(item=>item.evidence_id===relinkTargetId);if(!source?.fingerprint)return;sessionLinks.setHashing(source.evidence_id);render();const controller=new AbortController();
    try{const digest=await hashEvidenceFile(file,()=>{},controller.signal);const staged=createStagedSource(file,digest,store.document.state.evidence);if(digest===source.fingerprint.sha256){store.execute("evidence.relinked","evidence",source.evidence_id,"Confirmed an exact source-byte match for this browser session.",document=>{recordExactRelink(document.state.evidence,source.evidence_id,staged,document.state.profile);});sessionLinks.setExact(source.evidence_id,file);void persistRecovery();setToast("Exact byte match linked for this session.");}
      else{sessionLinks.setTransient(source.evidence_id,"mismatch");const exactOther=store.document.state.evidence.sources.find(item=>item.evidence_id!==source.evidence_id&&item.fingerprint?.sha256===digest);const message=exactOther?`The selected bytes do not match ${source.display_label}, but exactly match ${exactOther.display_label}. No governed record changed.`:`The selected bytes do not match ${source.display_label}. Create a new revision or cancel; the prior fingerprint cannot be replaced.`;const choice=await chooseDialog("Hash mismatch",message,[{value:"cancel",label:"Cancel"},...(exactOther?[{value:"other",label:"Link exact other source"}]:[]),{value:"revision",label:"Create new revision"}]);if(choice==="other"&&exactOther){store.execute("evidence.relinked","evidence",exactOther.evidence_id,"Confirmed selected bytes against another exact catalog source.",document=>{recordExactRelink(document.state.evidence,exactOther.evidence_id,staged,document.state.profile);});sessionLinks.setExact(exactOther.evidence_id,file);void persistRecovery();}
        else if(choice==="revision"){const values=await promptFields("Create source revision",[{name:"label",label:"Revision display label",value:`${source.display_label} revision`},{name:"rationale",label:"Revision rationale",type:"textarea",value:"Selected bytes changed and are retained as a new source revision."},{name:"supersede",label:"Supersede prior source? Enter yes or no",value:"yes"}]);if(values){staged.display_label=promptValue(values,"label");let revision:EvidenceSourceRecord|undefined;store.execute("evidence.create-revision","evidence",source.evidence_id,"Created a new source identity for changed bytes.",document=>{revision=createEvidenceRevision(document.state.evidence,source.evidence_id,staged,promptValue(values,"supersede").toLowerCase()==="yes",promptValue(values,"rationale"),document.state.profile);},"Created Evidence source revision");if(revision)sessionLinks.setExact(revision.evidence_id,file);void persistRecovery();setToast("New source revision created; prior fingerprint preserved.");}}else setToast("Relink cancelled. No Evidence record changed.");}
    }catch(error){sessionLinks.setTransient(source.evidence_id,(error as Error).name==="AbortError"?"cancelled":"error");await showMessage("Relink failed",errorMessage(error),true);}finally{relinkTargetId="";const input=document.getElementById("evidence-relink-input") as HTMLInputElement|null;if(input)input.value="";render();}
  }

  function archiveSource(id:string):void{try{store.execute("evidence.archive-source","evidence",id,"Archived an Evidence source reference.",document=>{const source=document.state.evidence.sources.find(item=>item.evidence_id===id);if(!source)throw new Error("Evidence source not found.");const group=source.duplicate_group_ref?document.state.evidence.duplicate_groups.find(item=>item.duplicate_group_id===source.duplicate_group_ref):undefined;if(group){const member=group.members.find(item=>item.source_ref===id);if(member?.disposition==="primary"&&group.members.some(item=>item.source_ref!==id&&item.disposition!=="excluded"))throw new Error("Select a reviewed replacement primary before archiving this duplicate-group primary.");}source.lifecycle="archived";source.updated_at=nowIso();});sessionLinks.unlink(id);void persistRecovery();setToast("Evidence source reference archived; no original file was deleted.");}catch(error){void showMessage("Archive failed",errorMessage(error),true);} }
  async function createCandidateForSource(id:string):Promise<void>{const source=store.document.state.evidence.sources.find(item=>item.evidence_id===id);if(!source)return;const values=await promptFields("Create Evidence candidate mapping",[{name:"target",label:"Target domain",value:"engagement"},{name:"type",label:"Target type",value:"open-question"},{name:"title",label:"Proposed title",value:`Confirm ${source.display_label}`},{name:"detail",label:"Proposed detail",type:"textarea",value:"Review this source-derived proposal in the target domain."},{name:"rationale",label:"Rationale",type:"textarea",value:"Evidence-origin proposal; target authority must decide."}]);if(!values)return;try{store.execute("evidence.create-candidate-mapping","evidence",id,"Created an Evidence-origin target proposal.",document=>{createEvidenceCandidate(document.state.evidence,{source_refs:[id],target_domain:promptValue(values,"target") as EvidenceTargetDomain,target_type:promptValue(values,"type"),proposed_operation:"create",proposed_fields:[{name:"title",value:promptValue(values,"title")},{name:"detail",value:promptValue(values,"detail")}],rationale:promptValue(values,"rationale")},document.state.profile);});void persistRecovery();evidenceTab="candidates";setToast("Candidate mapping created. Target accepted state is unchanged.");}catch(error){await showMessage("Candidate creation failed",errorMessage(error),true);} }
  function resolveDuplicate(id:string):void{const group=store.document.state.evidence.duplicate_groups.find(item=>item.duplicate_group_id===id);if(!group)return;const textarea=document.querySelector<HTMLTextAreaElement>(`[data-duplicate-rationale="${CSS.escape(id)}"]`);const dispositions:Record<string,DuplicateDisposition>={};group.members.forEach((member,index)=>{dispositions[member.source_ref]=index===0?"primary":"duplicate";});try{store.execute("evidence.set-duplicate-disposition","duplicate_group",id,"Resolved an exact duplicate group with explicit Advisor disposition.",document=>setDuplicateGroupDisposition(document.state.evidence,id,dispositions,textarea?.value??"",document.state.profile),"Resolved Evidence duplicate group");void persistRecovery();setToast("Duplicate group resolved; no source was deleted or merged.");}catch(error){void showMessage("Duplicate disposition failed",errorMessage(error),true);} }
  function publishCandidate(id:string):void{try{store.execute("evidence.publish-candidate-to-target","evidence_candidate",id,"Published an Evidence proposal into an Engagement-owned candidate.",document=>{const mapping=document.state.evidence.candidate_mappings.find(item=>item.candidate_id===id);if(!mapping)throw new Error("Evidence candidate not found.");const target=createEngagementCandidateFromEvidence(document.state.engagement,mapping,document.state.profile);markEvidenceCandidatePublished(mapping,target.candidate_id);});void persistRecovery();setToast("Published to an Engagement-owned candidate. Accepted Engagement state remains unchanged.");}catch(error){void showMessage("Candidate publication failed",errorMessage(error),true);} }
  function decideEngagement(id:string,action:"accept"|"reject"):void{try{store.execute(`engagement.candidate.${action}`,"candidate",id,`${action==="accept"?"Accepted":"Rejected"} an Engagement-owned candidate.`,document=>decideCandidate(document.state.engagement,id,action,"Explicit Advisor target-domain decision.",document.state.profile));void persistRecovery();setToast(`Engagement candidate ${action}ed by the owning domain.`);}catch(error){void showMessage("Engagement candidate decision failed",errorMessage(error),true);} }

  async function handlePackageFile(file:File):Promise<void>{try{let bytes=new Uint8Array(await file.arrayBuffer());if(bytes[0]===0x50&&bytes[1]===0x4b){const entries=readStoredZip(bytes);const jsonEntries=entries.filter(entry=>entry.path.toLowerCase().endsWith(".json"));if(jsonEntries.length!==1)throw new Error("A stored ZIP package must contain exactly one JSON payload for the v0.4 adapter.");bytes=jsonEntries[0]!.data;}pendingImport=await previewLegacyEvidencePackage(bytes,file.name);evidenceTab="imports";render();}catch(error){pendingImport=null;await showMessage("Package preview failed",errorMessage(error),true);}finally{const input=document.getElementById("package-import-input") as HTMLInputElement|null;if(input)input.value="";} }
  function applyPendingImport():void{if(!pendingImport)return;try{const preview=pendingImport;store.execute("evidence.apply-import","evidence_import",preview.package_sha256,"Applied a reviewed recognized package preview into Evidence authority.",document=>{applyImportPreview(document.state.evidence,preview,undefined,document.state.profile);},`Imported ${preview.package_kind}`);pendingImport=null;void persistRecovery();evidenceTab="catalog";setToast("Reviewed valid package records applied atomically. Target authority remains unchanged.");}catch(error){void showMessage("Import failed",errorMessage(error),true);} }

  async function downloadBytes(bytes:Uint8Array,fileName:string,type:string):Promise<void>{if(window.showSaveFilePicker){const handle=await window.showSaveFilePicker({suggestedName:fileName,types:[{description:"L2G encrypted project",accept:{[type]:[".l2g"]}}]});const writable=await handle.createWritable();await writable.write(new Blob([bytes],{type}));await writable.close();return;}const url=URL.createObjectURL(new Blob([bytes],{type}));const link=document.createElement("a");link.href=url;link.download=fileName;document.body.append(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
  interface PromptField {name:string;label:string;type?:"text"|"password"|"textarea";value?:string}
  function promptValue(values:Record<string,string>,name:string):string{return values[name]??"";}
  async function promptFields(title:string,fields:PromptField[]):Promise<Record<string,string>|null>{return new Promise(resolve=>{const dialog=document.createElement("dialog");dialog.innerHTML=`<form method="dialog"><h2>${h(title)}</h2>${fields.map(field=>`<div class="field"><label>${h(field.label)}${field.type==="textarea"?`<textarea name="${h(field.name)}">${h(field.value??"")}</textarea>`:`<input name="${h(field.name)}" type="${field.type==="password"?"password":"text"}" value="${h(field.value??"")}" ${field.type==="password"?'autocomplete="current-password"':""}>`}</label></div>`).join("")}<div class="dialog-actions"><button value="cancel">Cancel</button><button value="ok" class="primary">Continue</button></div></form>`;document.body.append(dialog);dialog.addEventListener("close",()=>{const result=dialog.returnValue==="ok"?Object.fromEntries(fields.map(field=>[field.name,(dialog.querySelector(`[name="${CSS.escape(field.name)}"]`) as HTMLInputElement|HTMLTextAreaElement).value])):null;dialog.remove();resolve(result);});dialog.showModal();(dialog.querySelector("input,textarea") as HTMLElement|null)?.focus();});}
  async function chooseDialog(title:string,message:string,choices:Array<{value:string;label:string}>):Promise<string>{return new Promise(resolve=>{const dialog=document.createElement("dialog");dialog.innerHTML=`<form method="dialog"><h2>${h(title)}</h2><p>${h(message)}</p><div class="dialog-actions">${choices.map(choice=>`<button value="${h(choice.value)}" ${choice.value!=="cancel"?'class="primary"':""}>${h(choice.label)}</button>`).join("")}</div></form>`;document.body.append(dialog);dialog.addEventListener("close",()=>{const value=dialog.returnValue||"cancel";dialog.remove();resolve(value);});dialog.showModal();});}
  async function showMessage(title:string,message:string,danger=false):Promise<void>{await chooseDialog(title,message,[{value:"ok",label:"OK"}]);if(danger)console.warn(`${title}: ${message}`);}

  document.getElementById("project-open-input")?.addEventListener("change",event=>{const file=(event.target as HTMLInputElement).files?.[0];if(file)void handleProjectOpen(file);});
  document.getElementById("evidence-add-input")?.addEventListener("change",event=>{const files=(event.target as HTMLInputElement).files;if(files?.length)void handleEvidenceFiles(files);});
  document.getElementById("evidence-relink-input")?.addEventListener("change",event=>{const file=(event.target as HTMLInputElement).files?.[0];if(file)void handleRelinkFile(file);});
  document.getElementById("package-import-input")?.addEventListener("change",event=>{const file=(event.target as HTMLInputElement).files?.[0];if(file)void handlePackageFile(file);});

  (window as unknown as Record<string,unknown>).__L2G_TEST__={store,sessionLinks,hashBytesInChunksForTest,createStagedSource,buildEvidenceProjection,searchEvidenceProjection,serializeInnerProject,deserializeInnerProject,deriveProjectKeys,encryptProjectDocument,decryptProjectBytes,previewLegacyEvidencePackage};
  store.subscribe(()=>render());
  render();
}
