
/* === v78 Contract-safe Reporting and SSP/Workbook Alignment === */
const V78_RELEASE=Object.freeze({
  name:"CMMC L2 Gap Workshop Tool",version:"v78",focus:"Contract-safe Reporting and SSP/Workbook Alignment",
  workshop_state:"1.0 additive",workbook_handoff:"1.7",workbook_merge:"1.1",ssp_handoff:"1.0",ssp_return:"1.0",
  adjacent_tool_consumption:false,local_only:true,new_stable_contract:false
});
const V78_REPORT_STATES=["accepted","requested","received","unavailable","deferred","closed"];
function v78Defaults(){return {schema_addition:"contract_safe_reporting_v78",version:"0.1-workshop-working",snapshots:[],ui:{report_audience:"advisor",record_audience:"all",practice:"",state:"all",flag:"all"},guardrails:{accepted_only:true,client_redaction:true,advisory_helper_only:true,consumer_may_ignore:true,no_downstream_acceptance:true,no_evidence_sufficiency_inference:true,no_assessment_conclusion:true,no_readiness_risk_compliance_or_certification:true,no_remote_workflow:true}};}
function v78Ensure(){if(!state.reportingV78||typeof state.reportingV78!=="object")state.reportingV78=v78Defaults();const d=v78Defaults(),g=state.reportingV78;Object.keys(d).forEach(k=>{if(g[k]===undefined)g[k]=v77Clone(d[k]);});g.snapshots=v77Arr(g.snapshots).slice(-30);g.ui={...d.ui,...(g.ui||{})};g.guardrails={...d.guardrails,...(g.guardrails||{})};return g;}
const v78DefaultStateBase=defaultState;
defaultState=function(){const b=v78DefaultStateBase();b.reportingV78=v78Defaults();return b;};
const v78NormalizeStateBase=normalizeState;
normalizeState=function(loaded){const b=v78NormalizeStateBase(loaded||{}),raw=loaded&&loaded.reportingV78&&typeof loaded.reportingV78==="object"?loaded.reportingV78:v78Defaults();b.reportingV78={...v78Defaults(),...raw,snapshots:v77Arr(raw.snapshots).slice(-30),ui:{...v78Defaults().ui,...(raw.ui||{})},guardrails:{...v78Defaults().guardrails,...(raw.guardrails||{})}};return b;};
function v78SafeClientText(v,max=900){let s=v77Txt(v,max);s=s.replace(/file:\/\/\S+/gi,"[local path removed]");s=s.replace(/(?:[A-Za-z]:\\(?:[^\\\s]+\\)+[^\\\s]*)/g,"[local path removed]");s=s.replace(/(?:\/Users\/|\/home\/|\/mnt\/|\/tmp\/)[^\s,;]+/g,"[local path removed]");s=s.replace(/\b(password|secret|token|api[_ -]?key)\s*[:=]\s*\S+/gi,"$1=[sensitive value removed]");return s;}
function v78AcceptedRows(){const g=v77Ensure(),accepted=v77Arr(g.accepted_records),acceptedIds=new Set(accepted.map(x=>x.ownership_record_id||x.candidate_id).filter(Boolean)),today=new Date().toISOString().slice(0,10);return [...acceptedIds].map(id=>{const a=accepted.find(x=>(x.ownership_record_id||x.candidate_id)===id)||{},live=g.candidates.find(x=>x.candidate_id===id)||a,req=g.requests.find(x=>x.ownership_record_id===id),fu=g.provider_followups.find(x=>x.ownership_record_id===id),actionId=req?.action_id||fu?.action_id||"",action=actionId&&typeof v67FindAction==="function"?v67FindAction(actionId):null,due=req?.due_date||fu?.due_date||action?.due_date||"",stateNow=req?.status||fu?.state||live.state||"accepted",overdue=!!(due&&due<today&&!['closed','received','superseded'].includes(stateNow)),unresolvedFollowup=["Provider","Shared"].includes(live.audience)&&(!fu||!["received","closed"].includes(fu.state));return {ownership_record_id:id,candidate_id:live.candidate_id||id,practice_id:live.practice_id||a.practice_id||"",practice_name:live.practice_name||a.practice_name||"",evidence_category:live.evidence_category||a.evidence_category||"",evidence_category_label:live.evidence_category_label||a.evidence_category_label||"",audience:live.audience||a.audience||"Client",production_owner:live.production_owner||a.production_owner||"",retention_owner:live.retention_owner||a.retention_owner||"",access_owner:live.access_owner||a.access_owner||"",access_path:live.access_path||a.access_path||"",submission_owner:live.submission_owner||a.submission_owner||"",review_followup_owner:live.review_followup_owner||a.review_followup_owner||"",contract_validation_required:!!(live.contract_validation_required??a.contract_validation_required),access_limitation:live.access_limitation||a.access_limitation||"",ownership_state:live.state||a.state||"accepted",request_id:req?.request_id||"",request_status:req?.status||"",provider_followup_id:fu?.followup_id||"",provider_followup_state:fu?.state||"",due_date:due,action_id:actionId,action_status:action?.status||"",blocker_id:action?.blocker_id||"",report_state:stateNow,overdue,unresolved_followup:unresolvedFollowup,service_names:v77Arr(live.service_names||a.service_names),responsibility_record_id:live.responsibility_record_id||a.responsibility_record_id||"",source_package_kind:live.source_package_kind||a.source_package_kind||"",source_package_version:live.source_package_version||a.source_package_version||"",source_fingerprint:live.source_fingerprint||a.source_fingerprint||"",advisor_note:live.advisor_note||a.advisor_note||"",validation_questions:v77Arr(live.validation_questions||a.validation_questions),accepted_at:a.accepted_at||live.accepted_at||"",accepted_by:a.accepted_by||live.accepted_by||""};}).sort((x,y)=>x.practice_id.localeCompare(y.practice_id)||x.evidence_category.localeCompare(y.evidence_category));}
function v78ClientRow(r){return {practice_id:r.practice_id,practice_name:v78SafeClientText(r.practice_name),evidence_category_label:v78SafeClientText(r.evidence_category_label),audience:r.audience,production_owner:v78SafeClientText(r.production_owner),retention_owner:v78SafeClientText(r.retention_owner),access_owner:v78SafeClientText(r.access_owner),access_path:v78SafeClientText(r.access_path),submission_owner:v78SafeClientText(r.submission_owner),review_followup_owner:v78SafeClientText(r.review_followup_owner),contract_validation_required:r.contract_validation_required,access_limitation:v78SafeClientText(r.access_limitation),request_status:r.request_status,provider_followup_state:r.provider_followup_state,due_date:r.due_date,report_state:r.report_state,overdue:r.overdue,unresolved_followup:r.unresolved_followup};}
function v78AdvisorRow(r){return v77Clone(r);}
function v78ReadFilters(){const g=v78Ensure(),val=(id,fallback)=>document.getElementById(id)?.value??fallback;g.ui={...g.ui,report_audience:val("v78ReportAudience",g.ui.report_audience),record_audience:val("v78RecordAudience",g.ui.record_audience),practice:v77Txt(val("v78PracticeFilter",g.ui.practice),120).toLowerCase(),state:val("v78StateFilter",g.ui.state),flag:val("v78FlagFilter",g.ui.flag)};v77Persist();return v77Clone(g.ui);}
function v78FilterRows(rows,filters=v78ReadFilters()){return rows.filter(r=>filters.record_audience==="all"||r.audience===filters.record_audience).filter(r=>!filters.practice||[r.practice_id,r.practice_name,r.evidence_category_label,r.service_names.join(" ")].join(" ").toLowerCase().includes(filters.practice)).filter(r=>filters.state==="all"||r.report_state===filters.state).filter(r=>filters.flag==="all"||(filters.flag==="contract"&&r.contract_validation_required)||(filters.flag==="access"&&!!v77Txt(r.access_limitation))||(filters.flag==="overdue"&&r.overdue)||(filters.flag==="unresolved"&&r.unresolved_followup));}
function v78CanonicalFilters(f){return {record_audience:f.record_audience||"all",practice:f.practice||"",state:f.state||"all",flag:f.flag||"all"};}
function v78BuildSnapshot(audience=(v78Ensure().ui.report_audience||"advisor"),remember=false){const filters=v78CanonicalFilters(v78ReadFilters()),base=v78FilterRows(v78AcceptedRows(),{...filters,report_audience:audience}),rows=audience==="client"?base.map(v78ClientRow):base.map(v78AdvisorRow),canonical={audience,filters,rows},content_fingerprint=v77Hash(canonical),snapshot_id=v77StableId("RPT78",[audience,content_fingerprint]),g=v78Ensure();let meta=g.snapshots.find(x=>x.snapshot_id===snapshot_id);if(remember&&!meta){meta={snapshot_id,audience,content_fingerprint,generated_at:new Date().toISOString(),row_count:rows.length};g.snapshots.push(meta);g.snapshots=g.snapshots.slice(-30);v77Record("v78_report_snapshot_generated",{snapshot_id,audience,row_count:rows.length});v77Persist();}return {document_kind:"workshop_contract_safe_report",format_version:"0.1-internal",snapshot_id,content_fingerprint,generated_at:meta?.generated_at||"preview-not-persisted",audience,filters,producer:{tool:"CMMC L2 Gap Workshop Tool",version:"v78"},authority_boundary:{workshop_authoritative_source:true,downstream_helper_only:true,consumer_may_ignore:true,downstream_acceptance_not_implied:true,no_evidence_sufficiency_or_assessment_conclusion:true},accepted_only:true,rows};}
function v78Summary(rows=v78AcceptedRows()){return {accepted_ownership:rows.length,client:rows.filter(x=>x.audience==="Client").length,provider:rows.filter(x=>x.audience==="Provider").length,shared:rows.filter(x=>x.audience==="Shared").length,requests:rows.filter(x=>x.request_id).length,provider_followups:rows.filter(x=>x.provider_followup_id).length,contract_validation:rows.filter(x=>x.contract_validation_required).length,access_limitations:rows.filter(x=>v77Txt(x.access_limitation)).length,overdue:rows.filter(x=>x.overdue).length,unresolved_followup:rows.filter(x=>x.unresolved_followup).length};}
function v78HelperSnapshot(target){const rows=v78AcceptedRows().map(r=>({ownership_record_id:r.ownership_record_id,practice_id:r.practice_id,evidence_category:r.evidence_category,evidence_category_label:r.evidence_category_label,audience:r.audience,production_owner:r.production_owner,retention_owner:r.retention_owner,access_owner:r.access_owner,access_path:r.access_path,submission_owner:r.submission_owner,review_followup_owner:r.review_followup_owner,contract_validation_required:r.contract_validation_required,access_limitation:r.access_limitation,request_id:r.request_id,request_status:r.request_status,provider_followup_id:r.provider_followup_id,provider_followup_state:r.provider_followup_state,due_date:r.due_date,action_id:r.action_id,report_state:r.report_state,source_responsibility_record_id:r.responsibility_record_id})),summary=v78Summary(v78AcceptedRows()),base={schema_addition:"optional_workshop_evidence_ownership_helper_v78",schema_version:"0.1",target,producer:{tool:"CMMC L2 Gap Workshop Tool",version:"v78"},source_contracts:{workshop_state:"1.0",workbook_handoff:"1.7",ssp_handoff:"1.0"},accepted_only:true,advisory_only:true,consumer_may_ignore:true,downstream_consumption_confirmed:false,does_not_overwrite_downstream_content:true,no_assessment_or_evidence_sufficiency_conclusions:true,summary,records:rows};base.snapshot_fingerprint=v77Hash(base);return base;}
function v78RehashPackage(p){if(p&&p.package_integrity&&typeof v56Fingerprint==="function")p.package_integrity.canonical_fingerprint=v56Fingerprint(p);return p;}
const v78WorkbookHandoffBase=l2gWorkbookHandoffPackage;
l2gWorkbookHandoffPackage=function(){const p=v78WorkbookHandoffBase();p.gap_workshop_tool_version="v78";p.ui_workflow_metadata={...(p.ui_workflow_metadata||{}),release:"v78",contract_safe_reporting:true,optional_evidence_ownership_helper:true,helper_consumed_by_builder_merger:false};p.optional_workshop_evidence_ownership_helper_v78=v78HelperSnapshot("workbook");return v78RehashPackage(p);};
function v78SspFactoryNames(){const explicit=["l2gSspHandoffPackage","l2gSSPHandoffPackage","sspHandoffPackage","v69SspHandoffPackage","v70SspHandoffPackage","v71SspHandoffPackage","v72SspHandoffPackage","v73SspHandoffPackage","v74SspHandoffPackage","v75SspHandoffPackage","v76SspHandoffPackage"],dynamic=Object.keys(window).filter(k=>/ssp.*handoff.*package/i.test(k)&&!/download|import|preview|handle|v78/i.test(k));return [...new Set([...explicit,...dynamic])].filter(k=>typeof window[k]==="function");}
function v78WrapSspHandoffFactories(){v78SspFactoryNames().forEach(name=>{const base=window[name];if(base.__v78Wrapped)return;const wrapped=function(...args){const p=base.apply(this,args);if(p&&typeof p==="object"&&String(p.package_kind||"").toLowerCase()==="l2g_ssp_handoff_v1"){p.gap_workshop_tool_version="v78";p.optional_workshop_evidence_ownership_helper_v78=v78HelperSnapshot("ssp");v78RehashPackage(p);}return p;};wrapped.__v78Wrapped=true;wrapped.__v78Base=base;window[name]=wrapped;});}
