const v78ObsBase=v69ObservabilityPackage;
v69ObservabilityPackage=function(){const p=v78ObsBase(),s=v78Summary();p.gap_workshop_tool_version="v78";p.counts={...(p.counts||{}),accepted_evidence_ownership_report_records:s.accepted_ownership,contract_safe_report_snapshots:v78Ensure().snapshots.length};p.optional_observability_contracts={...(p.optional_observability_contracts||{}),contract_safe_reporting_v78:"Workshop v78 count-only observability; report bodies and helper records excluded"};return p;};
const v78MatrixBase=v64RenderToolchainMatrix;
v64RenderToolchainMatrix=function(){const r=v78MatrixBase(),table=document.getElementById("v64ToolchainMatrix");if(table)[...table.querySelectorAll("tbody tr")].forEach(tr=>{const c=tr.querySelectorAll("td");if(c[0]?.textContent.includes("CMMC L2 Gap Workshop Tool")){if(c[1])c[1].textContent="v78";if(c[5])c[5].textContent="Workshop-authoritative accepted-only reporting with optional additive workbook/SSP helper snapshots; stable contracts preserved and no downstream consumption claimed";}});return r;};
const v78CompatibilityBase=v60CompatibilityManifest;
v60CompatibilityManifest=function(){const m=v78CompatibilityBase(),s=v78Summary();m.release=V78_RELEASE;m.version="v78";m.contract_safe_reporting_alignment={status:"workshop_internal_reporting_and_optional_helper",accepted_only:true,advisor_and_client_outputs:true,client_redaction:true,deterministic_snapshot_ids:true,print_friendly:true,formats:["html","markdown","json","csv"],optional_workbook_helper:true,optional_ssp_helper:true,helper_consumer_may_ignore:true,downstream_consumption_confirmed:false,new_stable_contract:false,counts:s};m.stable_contracts={...(m.stable_contracts||{}),workshop_state:"1.0 additive",workbook_handoff:"1.7 stable/frozen with optional ignorable helper",workbook_merge:"1.1 stable/frozen",ssp_handoff:"1.0 stable with optional ignorable helper",ssp_return:"1.0 validated"};m.adjacent_tool_release_required=false;m.adjacent_tool_actions=["Builder/Merger and SSP may ignore the optional v78 helper fields; current consumption is not claimed.","Workbook results and SSP authoring remain reviewer-controlled and are never overwritten.","The future SSP review/delivery profile remains separately governed and absent."];m.future_ssp_review_delivery_profile=false;return m;};
v60DownloadCompatibilityManifest=function(){download(datedFileName("CMMC_L2_Gap_Workshop_v78_Compatibility_Manifest","json"),JSON.stringify(v60CompatibilityManifest(),null,2),"application/json");showToast("v78 compatibility manifest exported.");};
const v78RuntimeBase=v60RuntimeChecks;
v60RuntimeChecks=function(){const r=v78RuntimeBase();r.checks=r.checks.filter(x=>x.id!=="version"&&!/^stable-handoff-v7/.test(x.id));const accepted=v78AcceptedRows(),client=JSON.stringify(v78BuildSnapshot("client",false)),helper=v78HelperSnapshot("workbook");r.checks.unshift({id:"version",label:"Visible/current release",actual:CRM_TOOL_VERSION,expected:"v78",pass:CRM_TOOL_VERSION==="v78"});r.checks.push({id:"v78-workspace",label:"Contract-safe reporting workspace",actual:!!document.getElementById("v78ReportingWorkspace"),expected:true,pass:!!document.getElementById("v78ReportingWorkspace")});r.checks.push({id:"v78-accepted-only",label:"Reporting derives only from accepted ownership records",actual:accepted.length,expected:v77Ensure().accepted_records.length,pass:accepted.length===new Set(v77Ensure().accepted_records.map(x=>x.ownership_record_id||x.candidate_id).filter(Boolean)).size});r.checks.push({id:"v78-client-redaction",label:"Client snapshot excludes advisor-only fields",actual:/advisor_note|source_fingerprint|validation_questions/i.test(client),expected:false,pass:!/advisor_note|source_fingerprint|validation_questions/i.test(client)});r.checks.push({id:"v78-helper-contract",label:"Optional helper preserves stable contracts",actual:{workbook:helper.source_contracts.workbook_handoff,ssp:helper.source_contracts.ssp_handoff,consumed:helper.downstream_consumption_confirmed},expected:{workbook:"1.7",ssp:"1.0",consumed:false},pass:helper.source_contracts.workbook_handoff==="1.7"&&helper.source_contracts.ssp_handoff==="1.0"&&helper.downstream_consumption_confirmed===false});r.checks.push({id:"stable-handoff-v78",label:"Workbook Handoff stable contract",actual:l2gWorkbookHandoffPackage().handoff_schema_enhancements_version||l2gWorkbookHandoffPackage().contract_manifest?.contract_release,expected:"1.7",pass:l2gWorkbookHandoffPackage().handoff_schema_enhancements_version==="1.7"||l2gWorkbookHandoffPackage().contract_manifest?.contract_release==="1.7"});r.checks.push({id:"v78-no-future-profile",label:"Future SSP review/delivery profile absent",actual:JSON.stringify(helper).includes("ssp_review_delivery_profile"),expected:false,pass:!JSON.stringify(helper).includes("ssp_review_delivery_profile")});r.passed=r.checks.filter(x=>x.pass).length;r.failed=r.checks.filter(x=>!x.pass).length;return r;};
const v78GuideBase=v69ToolchainOperatingGuideMarkdown;
v69ToolchainOperatingGuideMarkdown=function(){return v78GuideBase()+`\n## Contract-safe reporting and SSP/workbook alignment (Workshop v78)\n\nWorkshop v78 reports only explicitly accepted evidence-ownership records by default. Advisor outputs retain source linkage and internal review context; client outputs remove advisor notes, validation questions, source fingerprints, package-body detail, and local paths. Existing Workbook Handoff 1.7 and SSP Handoff 1.0 packages may carry an optional additive helper snapshot that older consumers may ignore. The helper does not overwrite downstream content, establish consumption, or imply evidence sufficiency, readiness, compliance, certification, or an assessment conclusion.\n`;};
function v78RegisterOutputs(){if(typeof V69_OUTPUTS!=="object")return;const add=(arr,item)=>{if(!arr.some(x=>x.title===item.title))arr.push(item);};add(V69_OUTPUTS.technical,{tag:"Reporting",title:"Workshop v78 Advisor Evidence Ownership Report",desc:"Accepted-only advisor report with provenance, request/follow-up status, and action linkage. No assessment conclusion.",action:"v78Ensure().ui.report_audience='advisor';v78Persist();v78Download('html')",label:"Download advisor HTML"});add(V69_OUTPUTS.client,{tag:"Reporting",title:"Workshop v78 Client-safe Evidence Ownership Summary",desc:"Accepted-only client summary with advisor-only fields and local paths removed.",action:"v78Ensure().ui.report_audience='client';v78Persist();v78Download('html')",label:"Download client HTML"});}
function v78UpdateCopy(){const card=document.querySelector(".scope-context-card");if(card&&card.textContent.includes("Current sync position"))card.innerHTML='<strong>Current sync position:</strong> Workshop v78 adds accepted-only advisor/client reporting and optional additive Workbook Handoff 1.7 / SSP Handoff 1.0 helper snapshots. Workshop remains authoritative; workbook and SSP content remain reviewer-controlled. No adjacent consumer, new stable contract, review/delivery profile, assessment conclusion, readiness, risk, compliance, certification, or scoring is introduced.';}
function v78InjectAll(){v78Ensure();v78WrapSspHandoffFactories();v78RegisterOutputs();v78InjectWorkspace();v78RenderWorkspace();v78UpdateCopy();v64RenderToolchainMatrix();try{document.documentElement.dataset.workshopVersion="v78";document.title="CMMC L2 Gap Workshop Tool v78";document.querySelectorAll(".hero h1 .small").forEach(x=>x.textContent="v78");}catch(e){}}
const v78RenderAllBase=renderAll;
renderAll=function(){const r=v78RenderAllBase();v78InjectAll();return r;};
function v78Init(){v78InjectAll();}
v78Init();
