 const oldJump=window.v792Jump;if(!window.__v796JumpPatched){window.v792Jump=function(id,action){if(action==='ocr'){const q=queueCore796(),i=q.items?.find(x=>x.id===id);if(i){W796.activeItemId=i.id;const d=findDoc796(i);if(d){W796.activeDocId=docId796(d);selectDoc796(d);}activateTab('trust');setTimeout(()=>{render796();$796('v796OcrWorkbench')?.scrollIntoView({behavior:'smooth',block:'start'});},80);return;}}return oldJump?.apply(this,arguments);};window.__v796JumpPatched=true;}
 observeStatus796();
}
function observeStatus796(){const el=$796('ocrStatus724');if(!el||el.__v796Observed)return;const obs=new MutationObserver(()=>{const t=el.textContent||'',m=t.match(/page\s+(\d+)\s+of\s+(\d+)/i),d=activeDoc796();if(d&&m&&W796.running){const src=sourceId796(),p=Number(m[1]);for(const x of requestedPages796(d))if(stateMap796(d)[pageKey796(src,x)]?.status==='processing')setPage796(d,src,x,'queued');setPage796(d,src,p,'processing');renderPages796(d);status796(t,'running');}});obs.observe(el,{subtree:true,childList:true,characterData:true});el.__v796Observed=true;W796.statusObserver=obs;}
function syncControls796(d){const count=pageCount796(d);W796.start=Math.max(1,Math.min(count,Number(W796.start)||1));W796.end=Math.max(W796.start,Math.min(count,Number(W796.end)||count));const scope=$796('v796Scope'),start=$796('v796Start'),end=$796('v796End');if(scope)scope.value=W796.scope;if(start){start.max=String(count);start.value=String(W796.start);}if(end){end.max=String(count);end.value=String(W796.end);}const isPdf=ext796(d)==='pdf';if(start)start.disabled=!isPdf||W796.scope==='all'||W796.scope==='remaining';if(end)end.disabled=!isPdf||W796.scope!=='range';}
function renderMetrics796(d){const m=metrics796(d),el=$796('v796Metrics');if(!el)return;const selectedLabel={native:'Native',ocr:'OCR',combined:'Combined',manual_review:'Manual review',pending_review:'Pending explicit review',metadata:'No text selected'}[m.selected]||m.selected;el.innerHTML=[['Native characters',m.native_chars],['Native readability',Math.round(m.native_score*100)+'%'],['OCR characters',m.ocr_chars],['OCR readability',Math.round(m.ocr_score*100)+'%'],['OCR confidence',d&&d.ocr_confidence!=null?Math.round(Number(d.ocr_confidence))+'%':'Not available'],['Selected analysis source',selectedLabel]].map(([l,v])=>'<div><strong>'+esc796(v)+'</strong><span>'+esc796(l)+'</span></div>').join('');$796('v796NativeMeta').textContent=m.native_chars+' characters • readability '+Math.round(m.native_score*100)+'% • '+(d&&d.extractionStatus||'native extraction');$796('v796OcrMeta').textContent=m.ocr_chars+' characters • readability '+Math.round(m.ocr_score*100)+'% • confidence '+(d&&d.ocr_confidence!=null?Math.round(Number(d.ocr_confidence))+'%':'not available');$796('v796NativeText').textContent=m.native||'No native text is available.';$796('v796OcrText').textContent=m.ocr||'No OCR text is available yet.';const decision=$796('v796Decision');if(decision)decision.value=['native','ocr','combined','manual_review'].includes(m.selected)?m.selected:'native';}
function renderPages796(d){const table=$796('v796Pages');if(!table)return;const m=stateMap796(d),src=sourceId796(),count=pageCount796(d),rows=[];const resultPages=new Set((d&&d.ocr_results||[]).filter(r=>String(r.source_id||'main')===src).map(r=>Number(r.page||1)));for(let p=1;p<=count;p++){const st=m[pageKey796(src,p)]||{},r=resultFor796(d,src,p),status=st.status||(resultPages.has(p)?'completed':'unprocessed');rows.push({p,status,attempts:st.attempts||0,chars:r?String(r.text||'').length:st.chars||0,confidence:r?Math.round(Number(r.confidence)||0):st.confidence??'',updated:st.updated_at||''});}table.innerHTML='<thead><tr><th>Page</th><th>Status</th><th>Attempts</th><th>Characters</th><th>Confidence</th><th>Last update</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+r.p+'</td><td><span class="v796-page '+esc796(r.status)+'">'+esc796(r.status.replace(/_/g,' '))+'</span></td><td>'+r.attempts+'</td><td>'+r.chars+'</td><td>'+(r.confidence!==''?r.confidence+'%':'—')+'</td><td>'+esc796(r.updated?new Date(r.updated).toLocaleTimeString():'—')+'</td></tr>').join('')+'</tbody>';}
function status796(msg,kind=''){const el=$796('v796Status');if(el){el.textContent=msg;el.className='v796-status '+kind;}}
function render796(){ensureUi796();const list=ocrItems796(),empty=$796('v796NoItems'),body=$796('v796Body');if(!list.length){if(empty)empty.hidden=false;if(body)body.hidden=true;return;}if(empty)empty.hidden=true;if(body)body.hidden=false;const item=activeItem796(),d=activeDoc796();if(!item||!d){status796('The selected queue item no longer maps to a source document. Refresh the queue.','warn');return;}selectDoc796(d);syncControls796(d);$796('v796File').textContent=base796(d.filename);$796('v796SourceMeta').textContent='Source ID: '+docId796(d)+' • '+ext796(d).toUpperCase()+' • '+pageCount796(d)+' page'+(pageCount796(d)===1?'':'s')+' • exception '+(list.indexOf(item)+1)+' of '+list.length;$796('v796Reason').innerHTML='<strong>Why OCR was recommended</strong><div>'+esc796(reason796(d,item))+'</div><div class="small">'+esc796(item.recommendation||'Run selective OCR only where native extraction is incomplete, then validate the recognized text against the source.')+'</div>';renderMetrics796(d);renderPages796(d);if(!W796.running)status796(d.ocr_status==='success'?'OCR results are available. Compare both representations and explicitly choose the analysis source.':'Ready. OCR remains optional and user initiated.','ready');}
function navigate796(delta){const list=ocrItems796();if(!list.length)return render796();let idx=list.findIndex(i=>i.id===W796.activeItemId);if(idx<0&&W796.activeDocId)idx=list.findIndex(i=>{const d=findDoc796(i);return d&&docId796(d)===W796.activeDocId;});if(idx<0)idx=0;idx=(idx+delta+list.length)%list.length;W796.activeItemId=list[idx].id;const d=findDoc796(list[idx]);if(d){W796.activeDocId=docId796(d);selectDoc796(d);W796.start=1;W796.end=pageCount796(d);}render796();$796('v796OcrWorkbench')?.scrollIntoView({behavior:'smooth',block:'start'});}
window.v796Previous=()=>navigate796(-1);window.v796Next=()=>navigate796(1);
window.v796ScopeChanged=function(){W796.scope=$796('v796Scope')?.value||'page';const d=activeDoc796();if(d&&W796.scope==='remaining'){const pages=requestedPages796(d,'remaining');W796.start=pages[0]||1;W796.end=pages[pages.length-1]||pageCount796(d);}syncControls796(d);renderPages796(d);};
window.v796RangeChanged=function(){W796.start=Math.max(1,Number($796('v796Start')?.value)||1);W796.end=Math.max(W796.start,Number($796('v796End')?.value)||W796.start);const d=activeDoc796();syncControls796(d);};
function decisionSnapshot796(d){return{doc:d,text:String(d&&d.text||''),sections:Array.isArray(d&&d.sections)?d.sections.slice():d&&d.sections,native:String(d&&d._native_text_v796||nativeText796(d)),preferred:d&&d.preferred_text_source,analysis:d&&d.ocr_analysis_source_v796,manual:d&&d.manual_override_used,readability:d&&d.readability,extractionStatus:d&&d.extractionStatus};}
function restorePendingReview796(snap){const d=snap&&snap.doc;if(!d||d.ocr_source_decision_locked_v796)return;d.text=snap.text;d.sections=snap.sections;d.readability=snap.readability;d.preferred_text_source=snap.preferred||((snap.native||'').trim()?'native':'metadata');d.ocr_analysis_source_v796='pending_review';d.ocr_review_required=true;d.extractionStatus='OCR result available; existing text retained pending explicit OCR Review Workbench decision';d.ocr_automatic_replacement_v796=false;}
