  }
  const pkg=PRIOR_PKG796(mode)||{};
  pkg.converter_version=V796;
  const reviewed=reviewedDocs796();
  if(!pkg.ocr_context||typeof pkg.ocr_context!=='object')pkg.ocr_context={};
  Object.assign(pkg.ocr_context,{workbench_release:V796,reviewed_documents:reviewed,native_and_ocr_separately_traceable:true,automatic_replacement:false,explicit_source_selection_required:true});
  if(pkg.scope_package_v1&&typeof pkg.scope_package_v1==='object')pkg.scope_package_v1.ocr_review_context={release:V796,reviewed_documents:reviewed,advisor_review_required:true,automatic_replacement:false};
  if(pkg.source_summary&&typeof pkg.source_summary==='object')Object.assign(pkg.source_summary,{roadmap_release:V796+' OCR Review Workbench and Batch Navigation',ocr_workbench_reviewed_documents:reviewed.length,ocr_page_state_tracking:true,ocr_explicit_source_selection:true});
  const selectedByFile=new Map(reviewed.map(r=>[String(r.source_file||'').toLowerCase(),r.selected_analysis_source]));
  const patchVisual=a=>{for(const r of Array.isArray(a)?a:[]){const v=selectedByFile.get(String(r.filename||r.source_file||r.document_name||'').toLowerCase());if(v){r.preferred_text_source=v;r.ocr_analysis_source_v796=v;if(r.ocr_quality_context&&typeof r.ocr_quality_context==='object')r.ocr_quality_context.preferred_source=v;}}};
  patchVisual(pkg.visual_document_context);patchVisual(pkg.scope_package_v1?.visual_document_context);patchVisual(pkg.scoper_support_context?.visual_document_context);
  return pkg;
 } finally {
  for(const x of snaps){x.d.text=x.text;x.d.sections=x.sections;x.d.manual_override_used=x.manual;x.d.preferred_text_source=x.preferred;x.d.ocr_analysis_source_v796=x.analysis;x.d.readability=x.readability;x.d.extractionStatus=x.extractionStatus;}
  PACKAGE_BUILDING796=false;
 }
};
pkg796.__v79Wrapped=true;pkg796.__v791Wrapped=true;pkg796.__v792Wrapped=true;pkg796.__v793Wrapped=true;pkg796.__v794Wrapped=true;pkg796.__v795Wrapped=true;pkg796.__v7951Wrapped=true;pkg796.__v796Wrapped=true;window.crmIntakePackage=pkg796;try{crmIntakePackage=window.crmIntakePackage;}catch(e){}
const PRIOR_DIAG796=window.docConverterReleaseDiagnostics;
const diag796=function(){return Object.assign({},PRIOR_DIAG796?PRIOR_DIAG796():{},{converter_version:V796,release_name:RELEASE796,cumulative_baseline:'v6.4-v7.9.5.1',ocr_review_workbench:{batch_navigation:true,queue_navigation:true,page_states:['queued','processing','completed','no_text','cancelled','failed','unprocessed'],scopes:['selected_page','page_range','remaining_pages','whole_document'],retry:'failed_or_unfinished_pages_only',cancellation_preserves_completed_results:true,native_ocr_side_by_side:true,explicit_analysis_source_selection:true,automatic_replacement:false,provenance_page_level:true},validation_question_candidate_precision_preserved:true,package_contract_changed:false,package_versions:{intake:'1.0',scope:'1.0',meeting:'1.0'},next_roadmap_release:'v7.9.7 Duplicate and Version Governance',roadmap_artifact:'DocConverter-L2G_v7.9.6_Next_10_Release_Roadmap.md'});};
diag796.__v79Wrapped=true;diag796.__v791Wrapped=true;diag796.__v792Wrapped=true;diag796.__v793Wrapped=true;diag796.__v794Wrapped=true;diag796.__v795Wrapped=true;diag796.__v7951Wrapped=true;diag796.__v796Wrapped=true;window.docConverterReleaseDiagnostics=diag796;try{docConverterReleaseDiagnostics=window.docConverterReleaseDiagnostics;}catch(e){}
function ensureMeeting796(){const api=window.DocConverterMeetingContext;if(!api||typeof api.buildPackage!=='function')return;if(!api.buildPackage.__v796Wrapped){const prior=api.buildPackage;const wrapped=function(){const p=prior.apply(this,arguments);if(p){p.converter_version=V796;p.ui_release=V796;}return p;};wrapped.__v796Wrapped=true;api.buildPackage=wrapped;}try{api.version=V796;}catch(e){}}
function identity796(){const title='DocConverter-L2G '+V796,footer='Offline single-file HTML. No network calls by default. DocConverter-L2G '+V796+'.';if(document.title!==title)document.title=title;if(document.documentElement.dataset.docConverterVersion!==V796)document.documentElement.dataset.docConverterVersion=V796;window.DOC_CONVERTER_VERSION=V796;document.querySelectorAll('.tool-version').forEach(n=>{if(n.textContent!==V796)n.textContent=V796;});document.querySelectorAll('footer').forEach(n=>{if(n.textContent!==footer)n.textContent=footer;});ensureMeeting796();}
function scheduleIdentity796(){for(const t of W796.identityTimers||[])clearTimeout(t);W796.identityTimers=[0,80,250,800,1700].map(ms=>setTimeout(identity796,ms));}
const PRIOR_RENDER796=window.renderAll;window.renderAll=function(){const r=PRIOR_RENDER796&&PRIOR_RENDER796.apply(this,arguments);scheduleIdentity796();return r;};try{renderAll=window.renderAll;}catch(e){}
const PRIOR_PREVIEW796=window.renderPreview;window.renderPreview=function(){const r=PRIOR_PREVIEW796&&PRIOR_PREVIEW796.apply(this,arguments);scheduleIdentity796();return r;};try{renderPreview=window.renderPreview;}catch(e){}
function startIdentityGuard796(){for(const t of [0,16,50,120,300,700,1200,1900,4300,8050,8300,8600])setTimeout(identity796,t);}
function init796(){for(const d of docs796())normalizePendingDoc796(d);ensureUi796();identity796();startIdentityGuard796();const p=$796('previewDoc');if(p&&!p.__v796){p.addEventListener('change',()=>{const d=selected796();if(d){W796.activeDocId=docId796(d);const i=ocrItems796().find(x=>findDoc796(x)===d);if(i)W796.activeItemId=i.id;}setTimeout(render796,50);});p.__v796=true;}const f=$796('fileInput');if(f&&!f.__v796){f.addEventListener('change',()=>{for(const t of [300,1200,3500,8000])setTimeout(()=>{ensureUi796();identity796();render796();},t);},{capture:false});f.__v796=true;}for(const t of [0,80,300,900,1800,4200])setTimeout(()=>{ensureUi796();identity796();render796();},t);window.__docconverter_release={...(window.__docconverter_release||{}),...window.docConverterReleaseDiagnostics()};}
window.DocConverterOcrReviewWorkbench=Object.freeze({version:V796,render:render796,run:window.v796Run,retry:window.v796Retry,cancel:window.v796Cancel,applyDecision:window.v796ApplyDecision,pageStates:d=>Object.values(stateMap796(d||activeDoc796())),items:ocrItems796,normalizePending:normalizePendingDoc796,localOnly:true,packageVersions:{intake:'1.0',scope:'1.0',meeting:'1.0'}});window.DocConverterIdentityStability=Object.freeze({version:V796,enforce:identity796,observer_count:0,observer_lifetime_ms:0,package_contract_changed:false});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init796,{once:true});else init796();
})();
