/* DocConverter-L2G v7.9.6 — OCR Review Workbench and Batch Navigation.
   Additive DocConverter-only release. Stable package kinds and base versions remain unchanged. */
(function(){
'use strict';
const V796='v7.9.6';
const RELEASE796='OCR Review Workbench and Batch Navigation';
const $796=id=>document.getElementById(id);
const clean796=(s,max=200000)=>{const t=String(s??'').replace(/\r/g,'\n').replace(/[\t ]+/g,' ').replace(/\n{3,}/g,'\n\n').trim();return t.length>max?t.slice(0,max).trim()+'…':t;};
const esc796=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base796=s=>String(s||'').split(/[\\/]/).pop();
const ext796=d=>String((d&&d.ext)||((base796(d&&d.filename||d||'').match(/\.([^.]+)$/)||[])[1]||'')).toLowerCase();
const docs796=()=>{try{return typeof state!=='undefined'&&Array.isArray(state.docs)?state.docs:[]}catch(e){return[]}};
const selected796=()=>{try{return typeof selectedDoc==='function'?selectedDoc():null}catch(e){return null}};
const score796=s=>{try{return typeof readabilityScore==='function'?Math.max(0,Math.min(1,Number(readabilityScore(String(s||'')))||0)):0}catch(e){return 0}};
function hash796(s){let h=2166136261;for(const c of String(s||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');}
function docId796(d){return String(d&&d.id||('doc-'+hash796(base796(d&&d.filename)+'|'+String(d&&d.size||0))));}
function stripEmbedded796(s){return String(s||'').replace(/\n*\[Embedded OCR v7\.2\.[0-9]+[\s\S]*$/,'').replace(/\n*\[Embedded OCR v7\.9\.6[\s\S]*$/,'').trim();}
function nativeText796(d){if(!d)return '';if(typeof d._native_text_v796==='string')return d._native_text_v796;let n='';if(typeof d.native_extracted_text==='string')n=d.native_extracted_text;else if(typeof d.pre_ocr_native_text==='string')n=d.pre_ocr_native_text;else if(typeof d.native_text==='string')n=d.native_text;else n=stripEmbedded796(d.text||'');n=String(n||'');try{Object.defineProperty(d,'_native_text_v796',{value:n,writable:true,configurable:true,enumerable:false});}catch(e){d._native_text_v796=n;}d.native_text_quality=score796(n);return n;}
function ocrText796(d){return String(d&&d.ocr_extracted_text||'').trim();}
function normalizePendingDoc796(d){if(!d||d.ocr_source_decision_locked_v796)return d;const o=ocrText796(d);if(!o)return d;const n=nativeText796(d),current=String(d.text||''),looksAuto=['ocr','native_plus_visual_ocr'].includes(String(d.preferred_text_source||''))||current.trim()===o.trim()||/^\[PDF page|^OCR PAGE|^\[Image/i.test(current.trim());if(looksAuto){d.text=n;try{if(typeof splitSections==='function')d.sections=splitSections(n);}catch(e){}d.readability=score796(n);}d.preferred_text_source=n.trim()?'native':'metadata';d.ocr_analysis_source_v796='pending_review';d.ocr_review_required=true;d.ocr_automatic_replacement_v796=false;d.extractionStatus='OCR representation available separately; explicit OCR Review Workbench source decision required';return d;}
function queueCore796(){return window.__DocConverterTrustQueue792||{items:[],resolutions:{}};}
function ocrItems796(){const q=queueCore796(),items=(q.items||[]).filter(i=>i&&i.trust_state==='unresolved'&&(i.category==='OCR'||i.category==='Readability')&&(i.source_document_id||i.source_file)),seen=new Set(items.map(i=>String(i.source_document_id||'')+'|'+base796(i.source_file).toLowerCase()));for(const d of docs796()){normalizePendingDoc796(d);const id=docId796(d),file=base796(d.filename),key=id+'|'+file.toLowerCase(),hasOcr=!!ocrText796(d);if(!hasOcr||seen.has(key))continue;const itemId='v796-ocr-review-'+hash796(id+'|'+file),res=q.resolutions?.[itemId];if(res&&['resolved','acknowledged','not_applicable'].includes(res.state))continue;const decided=!!d.ocr_source_decision_locked_v796;items.push({id:itemId,code:decided?'ocr-review-decision-recorded':'ocr-review-pending',category:'OCR',severity:decided?'Info':'Warning',trust_state:res?.state||'unresolved',title:(decided?'OCR source decision recorded for ':'OCR review pending for ')+file,reason:decided?'An explicit '+String(d.ocr_analysis_source_v796||d.preferred_text_source||'analysis-source')+' decision is recorded. Resolve or acknowledge this queue item after confirming the comparison and provenance.':'An OCR representation is available, but no operator has explicitly selected native, OCR, combined, or manual-review text for downstream drafting.',recommendation:decided?'Confirm the recorded source decision and resolve or acknowledge the queue item.':'Compare native and OCR text in the v7.9.6 workbench, record an explicit source decision, and then resolve or acknowledge this queue item.',source_file:file,source_document_id:id,source_fingerprint:d.fingerprint||d.sha256||'',doc_ids:[id],actions:['ocr'],affects:['intake','scope','meeting'],analysis_method:'v7.9.6 OCR Review Workbench',confidence:'High'});seen.add(key);}return items;}
function findDoc796(item){if(!item)return null;const ids=[item.source_document_id,...(item.doc_ids||[]),...(item.source_ids||[])].filter(Boolean).map(String);return docs796().find(d=>ids.includes(docId796(d))||ids.includes(String(d.id||'')))||docs796().find(d=>base796(d.filename).toLowerCase()===base796(item.source_file).toLowerCase())||null;}
function selectDoc796(d){if(!d)return false;const sel=$796('previewDoc');if(!sel)return false;const fn=base796(d.filename).toLowerCase();let idx=-1;for(let i=0;i<sel.options.length;i++){const o=sel.options[i],txt=String(o.textContent||'').toLowerCase(),val=String(o.value||'').toLowerCase();if(txt.includes(fn)||val===String(d.id||'').toLowerCase()||val===fn){idx=i;break;}}if(idx<0){const di=docs796().indexOf(d);if(di>=0&&di<sel.options.length)idx=di;}if(idx>=0){if(sel.selectedIndex!==idx)sel.selectedIndex=idx;return true;}return false;}
const W796=window.__DocConverterOcrWorkbench796||{activeItemId:'',activeDocId:'',scope:'page',start:1,end:1,cancelRequested:false,running:false,lastRun:null,statusObserver:null,renderTimer:null};
window.__DocConverterOcrWorkbench796=W796;
function stateMap796(d){if(!d)return{};if(!d.ocr_page_states_v796||typeof d.ocr_page_states_v796!=='object')d.ocr_page_states_v796={};return d.ocr_page_states_v796;}
function sourceId796(){return String($796('ocrSource724')?.value||'main');}
function pageKey796(src,page){return String(src||'main')+':'+String(page||1);}
function setPage796(d,src,page,status,extra={}){const m=stateMap796(d),k=pageKey796(src,page),prior=m[k]||{};m[k]=Object.assign({},prior,{source_id:src||'main',page:Number(page)||1,status,attempts:Number(prior.attempts||0)+(status==='queued'?1:0),updated_at:new Date().toISOString()},extra);return m[k];}
