from __future__ import annotations
import json
from pathlib import Path
from playwright.sync_api import Error as PlaywrightError,sync_playwright
ROOT=Path(__file__).resolve().parents[1];RUNTIME=ROOT/'CMMC_L2_SSP_Modern_Editable_v1.8.8.html';FIX=ROOT/'fixtures';fixture=json.loads((FIX/'Portfolio_CRM_McFirecoal_v1.8.8.json').read_text());errors=[]
with sync_playwright() as pw:
 executable='/usr/bin/chromium' if Path('/usr/bin/chromium').exists() else None;browser=pw.chromium.launch(headless=True,executable_path=executable,args=['--no-sandbox']);context=browser.new_context(accept_downloads=True,viewport={'width':1700,'height':1150});page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)));file_url_smoke=True
 try:page.goto(RUNTIME.as_uri(),wait_until='load')
 except PlaywrightError as error:
  if 'ERR_BLOCKED_BY_ADMINISTRATOR' not in str(error):raise
  file_url_smoke='blocked-by-local-browser-policy';page.close();page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)));page.set_content(RUNTIME.read_text(),wait_until='load')
 data=page.evaluate('()=>window.__sspTestHooks.collectData(true)');data['portfolioFoundation']=fixture;page.evaluate('(d)=>window.__sspTestHooks.applyData(d)',data)
 hooks=page.evaluate('()=>Object.keys(window.__sspTestHooks)');required=['portfolioBuildChangeDecisionRegister','portfolioRegisterCreateManualEntry','portfolioRegisterCounts','portfolioRegisterPackage','portfolioRegisterCsv'];assert all(x in hooks for x in required)
 state=fixture;admin={'person':'Alice Admin','role':'administrator'}
 r=page.evaluate('([s,t,a])=>window.__sspTestHooks.portfolioReviewAssignRole(s,t,a)',[state,{'person':'Alice Admin','role':'administrator','scope':'portfolio','moduleId':''},admin]);state=r['state']
 r=page.evaluate('([s,q,a])=>window.__sspTestHooks.portfolioRegisterCreateManualEntry(s,q,a)',[state,{'entryType':'decision','scope':'module','moduleId':'module-product-alpha','requirementId':'3.1.1','summary':'Use shared provider implementation with local supplement.','rationale':'The provider boundary and module evidence support this authoring decision.','outcome':'Preserve parent source and document local supplement.','relatedIds':'requirement-product-alpha-3_1_1'},admin]);state=r['state'];manual=r['entry'];assert manual['recordFingerprint'].startswith('fnv1a64-') and len(state['changeDecisionRegister'])==1
 missing_rationale=page.evaluate('([s,a])=>{try{window.__sspTestHooks.portfolioRegisterCreateManualEntry(s,{entryType:"decision",scope:"portfolio",summary:"No rationale"},a);return false}catch(e){return /rationale/i.test(e.message)}}',[state,admin]);assert missing_rationale
 unauthorized=page.evaluate('s=>{try{window.__sspTestHooks.portfolioRegisterCreateManualEntry(s,{entryType:"change",scope:"module",moduleId:"module-product-alpha",summary:"Unauthorized"},{person:"No Role",role:"author"});return false}catch(e){return /assignment/i.test(e.message)}}',state);assert unauthorized
 # Populate every required source category without mutating source records during aggregation.
 rich=json.loads(json.dumps(state));rich['exchangeHistory']=[{'exchangeId':'exchange-1','packageKind':'cmmc_l2_ssp_module_exchange_v1','packageVersion':'1.5','scope':'module','sourceFileName':'module.json','sourceFingerprint':'fnv1a64-1111111111111111','reportFingerprint':'fnv1a64-2222222222222222','importedAt':'2026-07-22T22:00:00Z','safe':2,'added':1,'unchanged':1,'conflicts':1,'invalid':0,'applied':3,'targetModuleId':'module-product-alpha'}]
 rich['crmReconciliations']=[{'reconciliationId':'crm-1','importedAt':'2026-07-22T22:01:00Z','sourceFileName':'crm.csv','sourceFingerprint':'fnv1a64-3333333333333333','importFormat':'modular','targetModuleId':'module-product-alpha','totalRows':110,'safeRows':2,'unchangedRows':107,'conflictRows':1,'invalidRows':0,'appliedRows':2,'reportFingerprint':'fnv1a64-4444444444444444'}]
 rich['moduleWordReviewQueues']={'module-product-alpha':{'reviewPackageId':'word-1','reviewScope':'module','portfolioId':rich['portfolio']['portfolioId'],'moduleId':'module-product-alpha','moduleName':'Product Alpha','sourceFingerprint':'fnv1a64-5555555555555555','sourceDocumentVersion':'1.0','sourceAppVersion':'1.8.8','sourceSchema':'test','exportedAt':'2026-07-22T22:02:00Z','importedAt':'2026-07-22T22:03:00Z','snapshotHash':'fnv1a64-6666666666666666','fileName':'alpha.docx','externalRelationshipsIgnored':0,'items':[{'id':'item-1'}]}}
 rec=next(x for x in rich['moduleRequirements'] if x['moduleId']=='module-product-alpha' and x['requirementId']=='3.1.1');rec.update({'impactDecisionId':'impact-1','impactReviewState':'preserved','impactReviewRationale':'Preserve local governed text.','impactReviewedAt':'2026-07-22T22:04:00Z','impactReviewedBy':'Alice Admin','impactSourceFingerprint':'fnv1a64-7777777777777777','impactChangedFields':['implementationNarrative']})
 rich['reviewSubmissions']=[{'submissionId':'submission-1','portfolioId':rich['portfolio']['portfolioId'],'moduleId':'module-product-alpha','scope':'module','round':1,'title':'Alpha review','message':'Review changes','submittedAt':'2026-07-22T22:05:00Z','submittedBy':'Alice Admin','submitterRole':'author','sourceFingerprint':'fnv1a64-8888888888888888','state':'ready-for-approval','updatedAt':'2026-07-22T22:06:00Z','withdrawnAt':'','withdrawnBy':''}]
 rich['reviewDispositions']=[{'dispositionId':'disposition-1','submissionId':'submission-1','portfolioId':rich['portfolio']['portfolioId'],'moduleId':'module-product-alpha','scope':'module','reviewer':'Alice Admin','reviewerRole':'reviewer','decision':'ready-for-approval','rationale':'Ready','recordedAt':'2026-07-22T22:06:00Z','sourceFingerprint':'fnv1a64-8888888888888888'}]
 rich['approvalRecords']=[{'approvalId':'approval-1','submissionId':'submission-1','portfolioId':rich['portfolio']['portfolioId'],'moduleId':'module-product-alpha','scope':'module','approver':'Alice Admin','approverRole':'approver','approvedAt':'2026-07-22T22:07:00Z','sourceFingerprint':'fnv1a64-8888888888888888','status':'active','rationale':'Approved','revokedAt':'','revokedBy':'','revocationReason':'','supersededAt':'','supersededBy':''}]
 rich['baselineEvents']=[{'eventId':'baseline-event-1','eventType':'created','baselineId':'baseline-1','eventAt':'2026-07-22T22:08:00Z','actor':'Alice Admin','reason':'Created','supersededByBaselineId':'','scope':'module','moduleId':'module-product-alpha'},{'eventId':'baseline-event-2','eventType':'restored','baselineId':'baseline-1','eventAt':'2026-07-22T22:09:00Z','actor':'Alice Admin','reason':'Restore for rework','supersededByBaselineId':'','scope':'module','moduleId':'module-product-alpha','restoredAsPortfolioVersion':'2.0','priorPortfolioVersion':'1.0'}]
 before=json.dumps(rich,sort_keys=True);entries=page.evaluate('s=>window.__sspTestHooks.portfolioBuildChangeDecisionRegister(s)',rich);after=json.dumps(rich,sort_keys=True);assert before==after
 categories={x['category'] for x in entries};required_categories={'change','decision','import','word-review','impact','conflict','review','approval','baseline','restoration'};assert required_categories.issubset(categories),required_categories-categories
 assert len({x['entryId'] for x in entries})==len(entries) and all(x['recordFingerprint'].startswith('fnv1a64-') for x in entries)
 counts=page.evaluate('e=>window.__sspTestHooks.portfolioRegisterCounts(e)',entries);assert counts['total']==len(entries) and counts['decisions']>=1
 pkg=page.evaluate('e=>window.__sspTestHooks.portfolioRegisterPackage(e)',entries);csv=page.evaluate('e=>window.__sspTestHooks.portfolioRegisterCsv(e)',entries);assert pkg['package_kind']=='cmmc_l2_ssp_change_decision_register_v1' and pkg['package_version']=='1.8' and pkg['register_fingerprint'].startswith('fnv1a64-');assert csv.count('\n')>=len(entries)
 # Render, filter, and export both formats.
 current=page.evaluate('()=>window.__sspTestHooks.collectData(true)');current['portfolioFoundation']=rich;page.evaluate('(d)=>window.__sspTestHooks.applyData(d)',current);page.evaluate('()=>document.querySelector("#portfolioSetupBtn").click()');page.wait_for_selector('#portfolioModal:not([hidden])');page.fill('#portfolioReviewActorName','Alice Admin');page.select_option('#portfolioReviewActorRole','administrator');page.locator('#portfolioRegisterCenter').scroll_into_view_if_needed();assert page.locator('#portfolioRegisterList .portfolio-register-row').count()>5
 page.select_option('#portfolioRegisterFilterCategory','restoration');assert page.locator('#portfolioRegisterList .portfolio-register-row').count()==1
 with page.expect_download() as event:page.click('#portfolioRegisterExportJsonBtn')
 exported=json.loads(Path(event.value.path()).read_text());assert exported['counts']['total']==1 and exported['entries'][0]['category']=='restoration'
 with page.expect_download() as event:page.click('#portfolioRegisterExportCsvBtn')
 exported_csv=Path(event.value.path()).read_text(encoding='utf-8-sig');assert 'restoration' in exported_csv and 'Record Fingerprint' in exported_csv
 page.select_option('#portfolioRegisterFilterCategory','');page.fill('#portfolioRegisterFilterSearch',manual['entryId']);assert page.locator('#portfolioRegisterList .portfolio-register-row').count()==1;page.click('#portfolioRegisterList .portfolio-register-row');assert manual['entryId'] in page.locator('#portfolioRegisterDetail').inner_text()
 screenshot=ROOT/'CMMC_L2_SSP_v1.8.8_Change_Decision_Register_Workbench.png';page.screenshot(path=str(screenshot),full_page=False);title=page.title();controls=page.locator('.control-card').count();context.close();browser.close()
assert not errors,errors
result={'release':'v1.8.8','suite':'browser-change-decision-register-regression','status':'passed','fileUrlSmoke':file_url_smoke,'title':title,'controls':controls,'entries':len(entries),'categories':sorted(categories),'manualEntry':manual['entryId'],'negative':{'missingRationaleRejected':missing_rationale,'unauthorizedRoleRejected':unauthorized},'exports':{'jsonEntries':exported['counts']['total'],'csv':True},'sourceMutation':False,'pageErrors':errors,'screenshot':screenshot.name}
(ROOT/'CMMC_L2_SSP_v1.8.8_Runtime_Regression.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result))
