namespace L2G {
  type V06ScopeTab = "boundary" | "objects" | "providers" | "flows" | "decisions" | "diagrams";
  interface V06TestHooks { store: ProjectStore; }
  let v06Tab:V06ScopeTab="boundary";
  let v06Selected="";
  let v06Preview:ScopeImportPreview|null=null;
  let v06Queued=false;

  function v06Hooks():V06TestHooks|null { return ((window as unknown as {__L2G_TEST__?:V06TestHooks}).__L2G_TEST__)??null; }
  function v06Scope(document:ProjectDocument):ScopeDomain { const value=document.state.scope;if(!value)throw new Error("The v0.6 Scope domain is missing.");return value; }
  function v06H(value:unknown):string { return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!)); }
  function v06Words(value:string):string { return value.replace(/-/g," ").replace(/\b\w/g,char=>char.toUpperCase()); }
  function v06Status(value:string):string { return /stale|conflict|blocked|rejected|returned|unknown|disputed/.test(value)?"attention":/accepted|reviewed|approved|complete|current/.test(value)?"success":""; }
  function v06Chip(label:string,value:string):string { return `<span class="scope-chip ${v06Status(value)}"><small>${v06H(label)}</small><strong>${v06H(v06Words(value))}</strong></span>`; }
  function v06Record(scope:ScopeDomain,id:string):ScopeRecordBase|undefined { return scopeRecordMap(scope).get(id); }

  function v06Queue():void { if(v06Queued)return;v06Queued=true;queueMicrotask(()=>{v06Queued=false;v06Enhance();}); }
  function v06Enhance():void {
    const hooks=v06Hooks();if(!hooks)return;
    const badge=document.querySelector<HTMLElement>(".release-badge");if(badge)badge.textContent=`v${window.__L2G_RELEASE__.version} · Scope Vertical Slice`;
    document.querySelectorAll<HTMLElement>(".notice,.qualification").forEach(node=>{if(node.textContent?.includes("v0.4"))node.textContent=node.textContent.replace(/v0\.4/g,"v0.6");});
    if(hooks.store.document.state.active_workspace!=="scope")return;
    const main=document.getElementById("workspace");if(!main||main.dataset.scopeV06==="ready")return;
    main.dataset.scopeV06="ready";v06Render(main,hooks.store);
  }

  function v06Render(main:HTMLElement,store:ProjectStore):void {
    const scope=v06Scope(store.document);refreshScopeCurrency(scope);const projection=buildScopeProjection(scope,store.document.state.profile);const selected=v06Selected?v06Record(scope,v06Selected):undefined;
    main.innerHTML=`${store.migrationNotice?`<div class="notice warning" role="status">${v06H(store.migrationNotice)}</div>`:""}<section class="scope-workbench" aria-labelledby="scope-title">
      <div class="workspace-header scope-header"><div><h1 id="scope-title">Scope</h1><p>Build an explicit, auditable boundary. Objects describe the environment; Scope-owned decisions establish accepted authority.</p></div><div class="workspace-actions">${store.document.state.profile==="advisor"?`<button id="v06-add-asset" class="primary">Add asset</button><button id="v06-import">Import Scoper package</button><button id="v06-diagram">Generate diagram</button>`:""}<span class="badge">${projection.next_work.filter(item=>item.kind!=="informational").length} visible next-work item${projection.next_work.filter(item=>item.kind!=="informational").length===1?"":"s"}</span></div></div>
      <div class="notice">Synthetic-only. Scope records and locally asserted data labels do not establish readiness, compliance, risk, evidence sufficiency, implementation, certification, or Met/Not Met.</div>
      <nav class="scope-tabs" aria-label="Scope views">${v06Tabs()}</nav>
      <div class="scope-metrics"><div><strong>${projection.counts.assets??0}</strong><span>assets</span></div><div><strong>${projection.counts.providers??0}</strong><span>providers</span></div><div><strong>${projection.counts.flows??0}</strong><span>flows</span></div><div><strong>${projection.counts.decisions??0}</strong><span>decisions</span></div><div><strong>${projection.counts.unknowns??0}</strong><span>unknowns</span></div><div><strong>${projection.counts.diagrams??0}</strong><span>diagrams</span></div></div>
      <div class="scope-layout"><div class="scope-canvas">${v06TabView(projection,scope,store.document.state.profile)}</div>${selected?v06Inspector(selected,scope,store.document.state.profile):`<aside class="scope-inspector empty-inspector"><h2>Inspector</h2><p>Select a visible Scope record to review identity, authority dimensions, provenance, decisions, and relationships.</p></aside>`}</div>
      ${v06Preview?v06ImportPanel(v06Preview):""}
      ${store.document.state.profile==="client"?`<div class="notice scope-client-qualification">This locally facilitated Scope view is not access control, an authenticated approval, an assessment conclusion, or authorization to distribute the complete project.</div>`:""}
    </section>`;
    v06Bind(main,store);
  }

  function v06Tabs():string { const labels:Record<V06ScopeTab,string>={boundary:"Boundary",objects:"Systems & Assets",providers:"Providers & Services",flows:"Data Flows",decisions:"Decisions",diagrams:"Diagrams"};return (Object.keys(labels) as V06ScopeTab[]).map(tab=>`<button data-v06-tab="${tab}" aria-current="${v06Tab===tab?"page":"false"}">${v06H(labels[tab])}</button>`).join(""); }
  function v06TabView(projection:ScopeProjection,scope:ScopeDomain,profile:PresentationProfile):string {
    if(v06Tab==="boundary")return v06Boundary(projection);
    if(v06Tab==="objects")return v06Objects([...projection.systems,...projection.assets],"No visible systems or assets.");
    if(v06Tab==="providers")return v06Objects([...projection.providers,...projection.services],"No visible providers or services.");
    if(v06Tab==="flows")return v06Flows(projection);
    if(v06Tab==="decisions")return v06Decisions(projection,profile);
    return v06Diagrams(projection,scope,profile);
  }
  function v06Boundary(projection:ScopeProjection):string {
    return `<div class="scope-grid"><section class="scope-panel"><div class="scope-panel-heading"><h2>Boundary records</h2><span>${projection.boundaries.length}</span></div>${projection.boundaries.map(item=>`<button class="scope-list-card" data-v06-ref="${v06H(item.id)}"><strong>${v06H(item.client_label||item.label)}</strong><small>${v06H(item.purpose)}</small><span>${v06Chip("Disposition",item.scope_disposition)}${v06Chip("Review",item.review_state)}${v06Chip("Currency",item.currency_state)}</span></button>`).join("")||`<div class="empty">No visible boundary exists. A migrated project intentionally starts with an empty Scope domain.</div>`}</section><section class="scope-panel"><div class="scope-panel-heading"><h2>Factual next work</h2><span>${projection.next_work.length}</span></div>${projection.next_work.slice(0,10).map(item=>`<button class="scope-list-card" data-v06-ref="${v06H(item.record_ref)}"><strong>${v06H(item.title)}</strong><small>${v06H(item.detail)}</small><span class="scope-priority">Priority ${item.priority}</span></button>`).join("")}</section></div>`;
  }
  function v06Objects(items:ScopeObject[],empty:string):string {
    if(!items.length)return `<div class="empty">${v06H(empty)}</div>`;
    return `<div class="scope-object-list">${items.map(item=>`<button class="scope-object-row" data-v06-ref="${v06H(item.id)}"><span><strong>${v06H(item.client_label||item.label)}</strong><small>${v06H(v06Words(item.family))} · ${v06H(v06Words(item.object_kind))}</small></span><span class="scope-dimensions">${v06Chip("Category",item.asset_category)}${v06Chip("Disposition",item.scope_disposition)}${v06Chip("Boundary",item.boundary_relationship)}${v06Chip("Location",item.implementation_location)}${v06Chip("Responsibility",item.responsibility_model)}</span></button>`).join("")}</div>`;
  }
  function v06Flows(projection:ScopeProjection):string {
    const labels=new Map<string,string>();[...projection.boundaries,...projection.systems,...projection.assets,...projection.providers,...projection.services,...projection.locations,...projection.enclaves].forEach(item=>labels.set(item.id,item.label));
    return projection.data_flows.length?`<div class="scope-flow-list">${projection.data_flows.map(flow=>`<button class="scope-flow-card" data-v06-ref="${v06H(flow.id)}"><strong>${v06H(flow.client_label||flow.label)}</strong><span class="scope-flow-path"><b>${v06H(labels.get(flow.source_ref)??"Unknown source")}</b><i>→</i>${flow.intermediary_refs.map(ref=>`<em>${v06H(labels.get(ref)??"Unknown intermediary")}</em><i>→</i>`).join("")}<b>${v06H(labels.get(flow.destination_ref)??"Unknown destination")}</b></span><small>${v06H(flow.data_description)}</small><span>${v06Chip("Data",flow.data_classification_label)}${v06Chip("Disposition",flow.scope_disposition)}${v06Chip("Currency",flow.currency_state)}</span></button>`).join("")}</div>`:`<div class="empty">No visible data flow exists.</div>`;
  }
  function v06Decisions(projection:ScopeProjection,profile:PresentationProfile):string {
    const decisions=projection.decisions.map(item=>`<article class="scope-decision-card"><button data-v06-ref="${v06H(item.id)}"><strong>${v06H(item.label)}</strong><small>${v06H(profile==="client"?item.client_safe_rationale:item.rationale)}</small><span>${v06Chip("Decision",item.decision_state)}${v06Chip("Review",item.review_state)}${v06Chip("Currency",item.currency_state)}</span></button>${profile==="advisor"&&["draft","proposed","awaiting-confirmation","awaiting-review","returned"].includes(item.decision_state)?`<div class="scope-card-actions"><button data-v06-accept-decision="${v06H(item.id)}" class="primary">Accept exact decision</button><button data-v06-return-decision="${v06H(item.id)}">Return</button></div>`:""}${profile==="reviewer"&&item.decision_state!=="accepted"?`<div class="scope-card-actions"><button data-v06-review="${v06H(item.id)}" data-v06-review-action="concur">Concur</button><button data-v06-review="${v06H(item.id)}" data-v06-review-action="return">Return</button><button data-v06-review="${v06H(item.id)}" data-v06-review-action="reject">Reject</button></div>`:""}</article>`).join("")||`<div class="empty">No visible Scope decisions.</div>`;
    const candidates=profile==="client"?"":projection.candidates.map(item=>`<article class="scope-candidate-card"><button data-v06-ref="${v06H(item.id)}"><strong>${v06H(item.label)}</strong><small>${v06H(v06Words(item.source_domain))} → ${v06H(v06Words(item.candidate_kind))}</small><span>${v06Chip("State",item.candidate_state)}</span></button>${profile==="advisor"&&(item.candidate_state==="received"||item.candidate_state==="in-review")?`<div class="scope-card-actions"><button data-v06-candidate="${v06H(item.id)}" data-v06-candidate-action="accept" class="primary">Accept candidate</button><button data-v06-candidate="${v06H(item.id)}" data-v06-candidate-action="return">Return</button><button data-v06-candidate="${v06H(item.id)}" data-v06-candidate-action="reject">Reject</button></div>`:""}</article>`).join("")||`<div class="empty">No Scope-owned candidate is waiting.</div>`;
    return `<div class="scope-grid"><section class="scope-panel"><div class="scope-panel-heading"><h2>Decision ledger</h2><span>${projection.decisions.length}</span></div>${decisions}</section>${profile!=="client"?`<section class="scope-panel"><div class="scope-panel-heading"><h2>Source candidates</h2><span>${projection.candidates.length}</span></div>${candidates}</section>`:""}</div>`;
  }
  function v06Diagrams(projection:ScopeProjection,scope:ScopeDomain,profile:PresentationProfile):string {
    if(!projection.diagrams.length)return `<div class="empty">No diagram is visible for this profile. Generated diagrams begin as drafts and do not create Scope authority.</div>`;
    return `<div class="scope-diagram-list">${projection.diagrams.map(diagram=>`<article class="scope-diagram-card"><div class="scope-diagram-heading"><button data-v06-ref="${v06H(diagram.id)}"><strong>${v06H(diagram.label)}</strong><small>${diagram.node_records.length} nodes · ${diagram.edge_records.length} edges</small></button><span>${v06Chip("Representation",diagram.diagram_review_state)}${v06Chip("Currency",diagram.currency_state)}</span></div><div class="scope-diagram-canvas" role="img" aria-label="${v06H(diagram.text_alternative)}">${diagram.node_records.map(node=>{const record=node.record_ref?v06Record(scope,node.record_ref.id):undefined;return `<button class="scope-diagram-node" data-v06-ref="${v06H(node.record_ref?.id??diagram.id)}" style="left:${Math.max(0,node.x)/4}px;top:${Math.max(0,node.y)/4}px">${v06H(record?.label??node.proposal_label??"Proposal")}</button>`;}).join("")}</div><details><summary>Accessible text alternative</summary><p>${v06H(diagram.text_alternative)}</p>${diagram.stale_ref_diagnostics.length?`<ul>${diagram.stale_ref_diagnostics.map(item=>`<li>${v06H(item)}</li>`).join("")}</ul>`:""}</details>${profile==="advisor"?`<div class="scope-card-actions"><button data-v06-refresh-diagram="${v06H(diagram.id)}">Refresh exact versions</button>${diagram.diagram_review_state!=="reviewed"?`<button data-v06-review-diagram="${v06H(diagram.id)}" class="primary">Mark reviewed</button>`:""}</div>`:""}</article>`).join("")}</div>`;
  }
  function v06Inspector(item:ScopeRecordBase,scope:ScopeDomain,profile:PresentationProfile):string {
    const related:string[]=[];if("related_refs" in item)related.push(...(item as ScopeObject).related_refs);if("included_refs" in item)related.push(...(item as ScopeBoundary).included_refs);if("affected_refs" in item)related.push(...(item as ScopeUnknown).affected_refs);const decisionRefs="decision_refs" in item?(item as unknown as {decision_refs:string[]}).decision_refs:[];
    return `<aside class="scope-inspector" aria-labelledby="scope-inspector-title"><div class="scope-inspector-heading"><div><h2 id="scope-inspector-title">${v06H(item.label)}</h2><p>${v06H(item.id)} · version ${item.version}</p></div><button id="v06-close" aria-label="Close Scope inspector">×</button></div><dl><dt>Authority</dt><dd>Scope</dd><dt>Lifecycle</dt><dd>${v06H(v06Words(item.lifecycle))}</dd><dt>Review</dt><dd>${v06H(v06Words(item.review_state))}</dd><dt>Visibility</dt><dd>${v06H(v06Words(item.visibility))}</dd><dt>Currency</dt><dd>${v06H(v06Words(item.currency_state))}</dd>${"asset_category" in item?`<dt>Category</dt><dd>${v06H(v06Words((item as ScopeObject).asset_category))}</dd><dt>Disposition</dt><dd>${v06H(v06Words((item as ScopeObject).scope_disposition))}</dd><dt>Boundary relationship</dt><dd>${v06H(v06Words((item as ScopeObject).boundary_relationship))}</dd><dt>Implementation location</dt><dd>${v06H(v06Words((item as ScopeObject).implementation_location))}</dd><dt>Responsibility</dt><dd>${v06H(v06Words((item as ScopeObject).responsibility_model))}</dd>`:""}</dl><h3>Description</h3><p>${v06H(item.description||("plain_language_summary" in item?String((item as unknown as {plain_language_summary:string}).plain_language_summary):"No additional description."))}</p><h3>Related records</h3>${related.length?`<div class="scope-related">${related.map(ref=>`<button data-v06-ref="${v06H(ref)}">${v06H(v06Record(scope,ref)?.label??ref)}</button>`).join("")}</div>`:`<p class="muted">No visible related records.</p>`}<h3>Governing decisions</h3>${decisionRefs.length?`<div class="scope-related">${decisionRefs.map(ref=>`<button data-v06-ref="${v06H(ref)}">${v06H(v06Record(scope,ref)?.label??ref)}</button>`).join("")}</div>`:`<p class="muted">No accepted Scope decision governs this record.</p>`}${profile!=="client"?`<h3>Provenance</h3><p>${v06H(item.provenance.source_label)}</p><p class="meta">${v06H(v06Words(item.provenance.origin_kind))} · ${v06H(item.provenance.asserted_at)}</p>`:""}</aside>`;
  }

  function v06Bind(main:HTMLElement,store:ProjectStore):void {
    main.querySelectorAll<HTMLButtonElement>("[data-v06-tab]").forEach(button=>button.addEventListener("click",()=>{v06Tab=button.dataset.v06Tab as V06ScopeTab;v06Selected="";v06Render(main,store);}));
    main.querySelectorAll<HTMLButtonElement>("[data-v06-ref]").forEach(button=>button.addEventListener("click",()=>{v06Selected=button.dataset.v06Ref??"";v06Render(main,store);}));
    main.querySelector("#v06-close")?.addEventListener("click",()=>{v06Selected="";v06Render(main,store);});
    main.querySelector("#v06-add-asset")?.addEventListener("click",()=>v06AddAsset(store));
    main.querySelector("#v06-import")?.addEventListener("click",()=>v06ChooseImport());
    main.querySelector("#v06-diagram")?.addEventListener("click",()=>v06GenerateDiagram(store));
    main.querySelectorAll<HTMLButtonElement>("[data-v06-candidate]").forEach(button=>button.addEventListener("click",()=>v06Candidate(store,button.dataset.v06Candidate??"",button.dataset.v06CandidateAction as "accept"|"return"|"reject")));
    main.querySelectorAll<HTMLButtonElement>("[data-v06-accept-decision]").forEach(button=>button.addEventListener("click",()=>v06Accept(store,button.dataset.v06AcceptDecision??"")));
    main.querySelectorAll<HTMLButtonElement>("[data-v06-return-decision]").forEach(button=>button.addEventListener("click",()=>v06ReturnDecision(store,button.dataset.v06ReturnDecision??"")));
    main.querySelectorAll<HTMLButtonElement>("[data-v06-review]").forEach(button=>button.addEventListener("click",()=>v06ReviewDecision(store,button.dataset.v06Review??"",button.dataset.v06ReviewAction??"return")));
    main.querySelectorAll<HTMLButtonElement>("[data-v06-refresh-diagram]").forEach(button=>button.addEventListener("click",()=>v06RefreshDiagram(store,button.dataset.v06RefreshDiagram??"")));
    main.querySelectorAll<HTMLButtonElement>("[data-v06-review-diagram]").forEach(button=>button.addEventListener("click",()=>v06ReviewDiagram(store,button.dataset.v06ReviewDiagram??"")));
    v06BindImport(main,store);
  }
  function v06AddAsset(store:ProjectStore):void {const label=window.prompt("Synthetic asset label","New synthetic asset");if(!label)return;const kind=window.prompt("Asset kind","cloud-resource")||"other";store.execute("scope.asset.created","scope_asset",newId("scope-action"),"Created a draft Scope asset.",document=>{createScopeAsset(v06Scope(document),{label,asset_kind:kind,visibility:"advisor-only",description:"Synthetic draft asset created for Scope review."},document.state.profile);});}
  function v06GenerateDiagram(store:ProjectStore):void {store.execute("scope.diagram.generated","scope_diagram",newId("scope-action"),"Generated a deterministic draft Scope diagram without changing object authority.",document=>{const scope=v06Scope(document);const ids=[...scope.boundaries,...scope.systems,...scope.assets,...scope.providers,...scope.services,...scope.data_flows].filter(item=>item.lifecycle!=="archived").slice(0,40).map(item=>item.id);if(!ids.length)throw new Error("No Scope records are available for a diagram.");scope.diagrams.push(createScopeDiagram(scope,`Scope diagram ${scope.diagrams.length+1}`,ids,document.state.profile));scope.updated_at=nowIso();scope.revision++;},"Generated Scope diagram draft");v06Tab="diagrams";}
  function v06Candidate(store:ProjectStore,id:string,action:"accept"|"return"|"reject"):void {const reason=window.prompt(`${v06Words(action)} candidate rationale`,action==="accept"?"Accepted into Scope as a target-owned draft record.":`${v06Words(action)}ed by Scope authority.`);if(!reason)return;store.execute(`scope.candidate.${action}`,"scope_candidate",id,`${v06Words(action)}ed a Scope-owned candidate.`,document=>{decideScopeCandidate(v06Scope(document),id,action,document.state.profile,reason);});}
  function v06Accept(store:ProjectStore,id:string):void {if(!window.confirm("Accept this exact-version Scope decision and update only the named Scope-owned fields?"))return;store.execute("scope.decision.accepted","scope_decision",id,"Accepted an exact-version Scope decision.",document=>{acceptScopeDecision(v06Scope(document),id,document.state.profile);},"Accepted Scope decision");}
  function v06ReturnDecision(store:ProjectStore,id:string):void {const comment=window.prompt("Return comment","Clarify source basis or affected exact version.");if(!comment)return;store.execute("scope.decision.returned","scope_decision",id,"Returned a Scope decision without changing governed object values.",document=>{const item=v06Scope(document).decisions.find(decision=>decision.id===id);if(!item)throw new Error("Scope decision not found.");item.decision_state="returned";item.review_state="changes-requested";item.reviewer_comment=sanitizePlainText(comment,100000);item.version++;item.updated_at=nowIso();});}
  function v06ReviewDecision(store:ProjectStore,id:string,action:string):void {const comment=window.prompt("Reviewer comment",action==="concur"?"Concur with this proposed Scope decision.":"Return for Advisor changes.")??"";store.execute(`scope.decision.reviewer-${action}`,"scope_decision",id,`Reviewer ${action} disposition recorded.`,document=>{const item=v06Scope(document).decisions.find(decision=>decision.id===id);if(!item)throw new Error("Scope decision not found.");item.reviewer_disposition=action==="concur"?"concur":action==="reject"?"reject":"return";item.reviewer_comment=sanitizePlainText(comment,100000);item.review_state=action==="concur"?"reviewed":action==="reject"?"rejected":"changes-requested";item.version++;item.updated_at=nowIso();});}
  function v06RefreshDiagram(store:ProjectStore,id:string):void {store.execute("scope.diagram.refreshed","scope_diagram",id,"Refreshed a diagram to current exact record versions.",document=>{const scope=v06Scope(document),item=scope.diagrams.find(diagram=>diagram.id===id);if(!item)throw new Error("Scope diagram not found.");const map=scopeRecordMap(scope);item.included_record_refs=item.included_record_refs.map(ref=>({id:ref.id,version:map.get(ref.id)?.version??ref.version}));item.node_records=item.node_records.map(node=>node.record_ref?{...node,record_ref:{id:node.record_ref.id,version:map.get(node.record_ref.id)?.version??node.record_ref.version}}:node);item.currency_state="current";item.stale_ref_diagnostics=[];item.diagram_review_state="draft";item.approval_decision_ref=null;item.version++;item.updated_at=nowIso();});}
  function v06ReviewDiagram(store:ProjectStore,id:string):void {store.execute("scope.diagram.reviewed","scope_diagram",id,"Marked a diagram reviewed as a representation; no object authority changed.",document=>{const item=v06Scope(document).diagrams.find(diagram=>diagram.id===id);if(!item)throw new Error("Scope diagram not found.");item.diagram_review_state="reviewed";item.review_state="reviewed";item.version++;item.updated_at=nowIso();});}

  function v06ChooseImport():void {const input=document.createElement("input");input.type="file";input.accept=".json,application/json";input.addEventListener("change",()=>{const file=input.files?.[0];if(file)void v06LoadImport(file);});input.click();}
  async function v06LoadImport(file:File):Promise<void> {try{v06Preview=await previewScopePackage(new Uint8Array(await file.arrayBuffer()),file.name);const main=document.getElementById("workspace"),hooks=v06Hooks();if(main&&hooks)v06Render(main,hooks.store);}catch(error){v06Preview=null;window.alert(`Scope package preview failed: ${errorMessage(error)}`);}}
  function v06ImportPanel(preview:ScopeImportPreview):string {return `<section class="scope-import-panel" aria-labelledby="v06-import-title"><div class="scope-inspector-heading"><div><h2 id="v06-import-title">Review Scope package</h2><p>${v06H(preview.package_kind)} ${v06H(preview.package_version)} · ${v06H(preview.package_name)}</p></div><button id="v06-close-import" aria-label="Close import preview">×</button></div><p class="mono">SHA-256 ${v06H(preview.package_sha256)}</p><div class="scope-import-records">${preview.records.map(item=>`<label><input type="checkbox" data-v06-import-record="${v06H(item.import_record_id)}" ${item.selected?"checked":""}><span><strong>${v06H(item.label)}</strong><small>${v06H(v06Words(item.family))} · ${v06H(item.source_path)}</small></span><select data-v06-treatment="${v06H(item.import_record_id)}"><option value="create" ${item.treatment==="create"?"selected":""}>Create candidate</option><option value="keep-separate" ${item.treatment==="keep-separate"?"selected":""}>Keep separate</option><option value="reject" ${item.treatment==="reject"?"selected":""}>Reject</option></select></label>`).join("")}</div>${preview.rejected.length||preview.warnings.length?`<div class="notice warning">${[...preview.warnings,...preview.rejected].map(item=>`<div>${v06H(item)}</div>`).join("")}</div>`:""}<div class="scope-card-actions"><button id="v06-reject-import">Reject preview</button><button id="v06-apply-import" class="primary">Apply reviewed subset atomically</button></div></section>`;}
  function v06BindImport(main:HTMLElement,store:ProjectStore):void {if(!v06Preview)return;main.querySelector("#v06-close-import")?.addEventListener("click",()=>{v06Preview=null;v06Render(main,store);});main.querySelector("#v06-reject-import")?.addEventListener("click",()=>{v06Preview=null;v06Render(main,store);});main.querySelectorAll<HTMLInputElement>("[data-v06-import-record]").forEach(input=>input.addEventListener("change",()=>{const item=v06Preview?.records.find(record=>record.import_record_id===input.dataset.v06ImportRecord);if(item)item.selected=input.checked;}));main.querySelectorAll<HTMLSelectElement>("[data-v06-treatment]").forEach(select=>select.addEventListener("change",()=>{const item=v06Preview?.records.find(record=>record.import_record_id===select.dataset.v06Treatment);if(item)item.treatment=select.value as ScopeImportCandidate["treatment"];}));main.querySelector("#v06-apply-import")?.addEventListener("click",()=>{if(!v06Preview)return;const preview=v06Preview;store.execute("scope.import.applied","scope_import",preview.package_sha256,"Applied a reviewed Scope package subset atomically as low-authority candidates.",document=>{applyScopeImport(v06Scope(document),preview,document.state.profile);},"Applied Scope compatibility package");v06Preview=null;v06Tab="decisions";});}

  const v06Observer=new MutationObserver(()=>v06Queue());const v06Root=document.getElementById("app");if(v06Root)v06Observer.observe(v06Root,{childList:true,subtree:true});v06Queue();
}
