namespace L2G {
  type ScopeTab = "boundary" | "objects" | "providers" | "flows" | "decisions" | "diagrams";
  interface ScopeTestHooks { store: ProjectStore; }
  let scopeTab:ScopeTab="boundary";
  let selectedScopeRef="";
  let pendingScopeImport:ScopeImportPreview|null=null;
  let scopeEnhanceQueued=false;
  let scopeImportInput:HTMLInputElement|null=null;

  function scopeHooks():ScopeTestHooks|null { return ((window as unknown as {__L2G_TEST__?:ScopeTestHooks}).__L2G_TEST__)??null; }
  function scopeDomain(store:ProjectStore):ScopeDomain { const scope=store.document.state.scope;if(!scope)throw new Error("The v0.6 Scope domain is missing.");return scope; }
  function sh(value:unknown):string { return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!)); }
  function familyLabel(value:string):string { return value.replace(/-/g," ").replace(/\b\w/g,char=>char.toUpperCase()); }
  function statusClass(value:string):string { return /stale|conflict|blocked|rejected|returned|unknown|disputed/.test(value)?"attention":/accepted|reviewed|approved|complete|current/.test(value)?"success":""; }
  function scopeRecordById(scope:ScopeDomain,id:string):ScopeRecordBase|undefined { return scopeRecordMap(scope).get(id); }

  function ensureScopeInput():HTMLInputElement {
    if(scopeImportInput&&document.body.contains(scopeImportInput))return scopeImportInput;
    const input=document.createElement("input");input.type="file";input.accept=".json,application/json";input.hidden=true;input.id="scope-import-input-v06";
    input.addEventListener("change",()=>{const file=input.files?.[0];if(file)void loadScopePackage(file);input.value="";});document.body.append(input);scopeImportInput=input;return input;
  }

  function queueScopeEnhance():void { if(scopeEnhanceQueued)return;scopeEnhanceQueued=true;queueMicrotask(()=>{scopeEnhanceQueued=false;enhanceScope();}); }
  function enhanceScope():void {
    const hooks=scopeHooks();if(!hooks)return;
    const badge=document.querySelector<HTMLElement>(".release-badge");if(badge)badge.textContent=`v${window.__L2G_RELEASE__.version} · Scope Vertical Slice`;
    document.querySelectorAll<HTMLElement>(".notice,.qualification").forEach(node=>{if(node.textContent?.includes("v0.4"))node.textContent=node.textContent.replace(/v0\.4/g,"v0.6");if(node.textContent?.includes("Evidence Catalog Core"))node.textContent=node.textContent.replace("Evidence Catalog Core","Scope Vertical Slice");});
    if(hooks.store.document.state.active_workspace!=="scope")return;
    const main=document.getElementById("workspace");if(!main||main.dataset.scopeV06==="ready")return;
    main.dataset.scopeV06="ready";renderScopeWorkspace(main,hooks.store);
  }

  function renderScopeWorkspace(main:HTMLElement,store:ProjectStore):void {
    const scope=scopeDomain(store);refreshScopeCurrency(scope);const projection=buildScopeProjection(scope,store.document.state.profile);const selected=selectedScopeRef?scopeRecordById(scope,selectedScopeRef):undefined;
    main.innerHTML=`${store.migrationNotice?`<div class="notice warning" role="status">${sh(store.migrationNotice)}</div>`:""}<section class="scope-workbench" aria-labelledby="scope-title">
      <div class="workspace-header scope-header"><div><h1 id="scope-title">Scope</h1><p>Build an explicit, auditable boundary. Objects describe the environment; Scope-owned decisions establish accepted authority.</p></div><div class="workspace-actions">${store.document.state.profile==="advisor"?`<button id="scope-add-asset" class="primary">Add asset</button><button id="scope-import">Import Scoper package</button><button id="scope-generate-diagram">Generate diagram</button>`:""}<span class="badge">${projection.next_work.filter(item=>item.kind!=="informational").length} visible next-work item${projection.next_work.filter(item=>item.kind!=="informational").length===1?"":"s"}</span></div></div>
      <div class="notice">Synthetic-only. Scope records and locally asserted data labels do not establish readiness, compliance, risk, evidence sufficiency, implementation, certification, or Met/Not Met.</div>
      <nav class="scope-tabs" aria-label="Scope views">${renderScopeTabs()}</nav>
      <div class="scope-metrics" aria-label="Visible Scope counts"><div><strong>${projection.counts.assets??0}</strong><span>assets</span></div><div><strong>${projection.counts.providers??0}</strong><span>providers</span></div><div><strong>${projection.counts.flows??0}</strong><span>flows</span></div><div><strong>${projection.counts.decisions??0}</strong><span>decisions</span></div><div><strong>${projection.counts.unknowns??0}</strong><span>unknowns</span></div><div><strong>${projection.counts.diagrams??0}</strong><span>diagrams</span></div></div>
      <div class="scope-layout"><div class="scope-canvas">${renderScopeTab(projection,scope,store.document.state.profile)}</div>${selected?renderScopeInspector(selected,scope,store.document.state.profile):`<aside class="scope-inspector empty-inspector"><h2>Inspector</h2><p>Select a visible Scope record to review exact identity, authority dimensions, provenance, decisions, and relationships.</p></aside>`}</div>
      ${store.document.state.profile==="client"?`<div class="notice scope-client-qualification">This locally facilitated Scope view is not access control, an authenticated approval, an assessment conclusion, or authorization to distribute the complete project.</div>`:""}
    </section>`;
    bindScopeWorkspace(main,store);
  }
  function renderScopeTabs():string { const labels:Record<ScopeTab,string>={boundary:"Boundary",objects:"Systems & Assets",providers:"Providers & Services",flows:"Data Flows",decisions:"Decisions",diagrams:"Diagrams"};return (Object.keys(labels) as ScopeTab[]).map(tab=>`<button data-scope-tab="${tab}" aria-current="${scopeTab===tab?"page":"false"}">${sh(labels[tab])}</button>`).join(""); }

  function renderScopeTab(projection:ScopeProjection,scope:ScopeDomain,profile:PresentationProfile):string {
    if(scopeTab==="boundary")return renderBoundaryView(projection);
    if(scopeTab==="objects")return renderObjectView([...projection.systems,...projection.assets],"No visible systems or assets.");
    if(scopeTab==="providers")return renderObjectView([...projection.providers,...projection.services],"No visible providers or services.");
    if(scopeTab==="flows")return renderFlowView(projection);
    if(scopeTab==="decisions")return renderDecisionView(projection,profile);
    return renderDiagramView(projection,scope,profile);
  }
  function stateChip(label:string,value:string):string { return `<span class="scope-chip ${statusClass(value)}"><span>${sh(label)}</span><strong>${sh(familyLabel(value))}</strong></span>`; }
  function renderBoundaryView(projection:ScopeProjection):string {
    const next=projection.next_work.slice(0,8);
    return `<div class="scope-grid"><section class="scope-panel"><div class="scope-panel-heading"><h2>Boundary records</h2><span>${projection.boundaries.length}</span></div>${projection.boundaries.length?projection.boundaries.map(item=>`<button class="scope-list-card" data-scope-ref="${sh(item.id)}"><strong>${sh(item.client_label||item.label)}</strong><small>${sh(item.purpose)}</small><span>${stateChip("Disposition",item.scope_disposition)} ${stateChip("Review",item.review_state)} ${stateChip("Currency",item.currency_state)}</span></button>`).join(""):`<div class="empty">No visible boundary record exists. A migrated project intentionally starts with an empty Scope domain.</div>`}</section>
      <section class="scope-panel"><div class="scope-panel-heading"><h2>Factual next work</h2><span>${next.length}</span></div>${next.map(item=>`<button class="scope-list-card" data-scope-ref="${sh(item.record_ref)}"><strong>${sh(item.title)}</strong><small>${sh(item.detail)}</small><span class="scope-priority">Priority ${item.priority}</span></button>`).join("")}</section></div>`;
  }
  function renderObjectView(items:ScopeObject[],empty:string):string {
    if(!items.length)return `<div class="empty">${sh(empty)}</div>`;
    return `<div class="scope-object-list">${items.map(item=>`<button class="scope-object-row" data-scope-ref="${sh(item.id)}"><span><strong>${sh(item.client_label||item.label)}</strong><small>${sh(familyLabel(item.family))} · ${sh(familyLabel(item.object_kind))}</small></span><span class="scope-dimensions">${stateChip("Category",item.asset_category)}${stateChip("Disposition",item.scope_disposition)}${stateChip("Boundary",item.boundary_relationship)}${stateChip("Location",item.implementation_location)}${stateChip("Responsibility",item.responsibility_model)}</span></button>`).join("")}</div>`;
  }
  function renderFlowView(projection:ScopeProjection):string {
    const map=new Map<string,ScopeRecordBase>();[...projection.boundaries,...projection.systems,...projection.assets,...projection.providers,...projection.services,...projection.locations,...projection.enclaves,...projection.data_flows].forEach(item=>map.set(item.id,item));
    if(!projection.data_flows.length)return `<div class="empty">No visible data-flow record exists.</div>`;
    return `<div class="scope-flow-list">${projection.data_flows.map(flow=>`<button class="scope-flow-card" data-scope-ref="${sh(flow.id)}"><strong>${sh(flow.client_label||flow.label)}</strong><span class="scope-flow-path"><b>${sh(map.get(flow.source_ref)?.label??"Unknown source")}</b><i>→</i>${flow.intermediary_refs.map(ref=>`<em>${sh(map.get(ref)?.label??"Unknown intermediary")}</em><i>→</i>`).join("")}<b>${sh(map.get(flow.destination_ref)?.label??"Unknown destination")}</b></span><small>${sh(flow.data_description)}</small><span>${stateChip("Data",flow.data_classification_label)}${stateChip("Disposition",flow.scope_disposition)}${stateChip("Currency",flow.currency_state)}</span></button>`).join("")}</div>`;
  }
  function renderDecisionView(projection:ScopeProjection,profile:PresentationProfile):string {
    const candidates=profile==="client"?[]:projection.candidates;
    return `<div class="scope-grid"><section class="scope-panel"><div class="scope-panel-heading"><h2>Decision ledger</h2><span>${projection.decisions.length}</span></div>${projection.decisions.map(item=>`<article class="scope-decision-card"><button data-scope-ref="${sh(item.id)}"><strong>${sh(item.label)}</strong><small>${sh(profile==="client"?item.client_safe_rationale:item.rationale)}</small><span>${stateChip("Decision",item.decision_state)}${stateChip("Review",item.review_state)}${stateChip("Currency",item.currency_state)}</span></button>${profile==="advisor"&&["draft","proposed","awaiting-confirmation","awaiting-review","returned"].includes(item.decision_state)?`<div class="scope-card-actions"><button data-scope-accept-decision="${sh(item.id)}" class="primary">Accept exact decision</button><button data-scope-return-decision="${sh(item.id)}">Return</button></div>`:""}${profile==="reviewer"&&item.decision_state!=="accepted"?`<div class="scope-card-actions"><button data-scope-review-decision="${sh(item.id)}" data-scope-review-action="concur">Concur</button><button data-scope-review-decision="${sh(item.id)}" data-scope-review-action="return">Return</button><button data-scope-review-decision="${sh(item.id)}" data-scope-review-action="reject">Reject</button></div>`:""}</article>`).join("")||`<div class="empty">No visible Scope decisions.</div>`}</section>
      ${profile!=="client"?`<section class="scope-panel"><div class="scope-panel-heading"><h2>Source candidates</h2><span>${candidates.length}</span></div>${candidates.map(item=>`<article class="scope-candidate-card"><button data-scope-ref="${sh(item.id)}"><strong>${sh(item.label)}</strong><small>${sh(familyLabel(item.source_domain))} → ${sh(familyLabel(item.candidate_kind))}</small><span>${stateChip("State",item.candidate_state)}</span></button>${profile==="advisor"&&(item.candidate_state==="received"||item.candidate_state==="in-review")?`<div class="scope-card-actions"><button data-scope-candidate="${sh(item.id)}" data-scope-candidate-action="accept" class="primary">Accept candidate</button><button data-scope-candidate="${sh(item.id)}" data-scope-candidate-action="return">Return</button><button data-scope-candidate="${sh(item.id)}" data-scope-candidate-action="reject">Reject</button></div>`:""}</article>`).join("")||`<div class="empty">No Scope-owned candidate is waiting.</div>`}</section>`:""}</div>`;
  }
  function renderDiagramView(projection:ScopeProjection,scope:ScopeDomain,profile:PresentationProfile):string {
    if(!projection.diagrams.length)return `<div class="empty">No diagram is visible for this profile. Generated diagrams begin as drafts and do not create Scope authority.</div>`;
    return `<div class="scope-diagram-list">${projection.diagrams.map(diagram=>`<article class="scope-diagram-card"><div class="scope-diagram-heading"><button data-scope-ref="${sh(diagram.id)}"><strong>${sh(diagram.label)}</strong><small>${sh(familyLabel(diagram.diagram_kind))} · ${diagram.node_records.length} nodes · ${diagram.edge_records.length} edges</small></button><span>${stateChip("Representation",diagram.diagram_review_state)}${stateChip("Currency",diagram.currency_state)}</span></div><div class="scope-diagram-canvas" role="img" aria-label="${sh(diagram.text_alternative)}">${diagram.node_records.map(node=>{const record=node.record_ref?scopeRecordById(scope,node.record_ref.id):undefined;return `<button class="scope-diagram-node" data-scope-ref="${sh(node.record_ref?.id??diagram.id)}" style="left:${Math.max(0,node.x)/4}px;top:${Math.max(0,node.y)/4}px">${sh(record?.label??node.proposal_label??"Proposal")}</button>`;}).join("")}</div><details><summary>Accessible text alternative</summary><p>${sh(diagram.text_alternative)}</p>${diagram.stale_ref_diagnostics.length?`<ul>${diagram.stale_ref_diagnostics.map(item=>`<li>${sh(item)}</li>`).join("")}</ul>`:""}</details>${profile==="advisor"?`<div class="scope-card-actions"><button data-scope-refresh-diagram="${sh(diagram.id)}">Refresh exact versions</button>${diagram.diagram_review_state!=="reviewed"?`<button data-scope-review-diagram="${sh(diagram.id)}" class="primary">Mark reviewed</button>`:""}</div>`:""}</article>`).join("")}</div>`;
  }

  function renderScopeInspector(item:ScopeRecordBase,scope:ScopeDomain,profile:PresentationProfile):string {
    const related:string[]=[];if("related_refs" in item)related.push(...(item as ScopeObject).related_refs);if("included_refs" in item)related.push(...(item as ScopeBoundary).included_refs);if("affected_refs" in item)related.push(...(item as ScopeUnknown).affected_refs);const decisionRefs="decision_refs" in item?(item as unknown as {decision_refs:string[]}).decision_refs:[];
    return `<aside class="scope-inspector" aria-labelledby="scope-inspector-title"><div class="scope-inspector-heading"><div><h2 id="scope-inspector-title">${sh(item.label)}</h2><p>${sh(item.id)} · version ${item.version}</p></div><button id="scope-close-inspector" aria-label="Close Scope inspector">×</button></div><dl><dt>Authority</dt><dd>Scope</dd><dt>Lifecycle</dt><dd>${sh(familyLabel(item.lifecycle))}</dd><dt>Review</dt><dd>${sh(familyLabel(item.review_state))}</dd><dt>Visibility</dt><dd>${sh(familyLabel(item.visibility))}</dd><dt>Currency</dt><dd>${sh(familyLabel(item.currency_state))}</dd>${"asset_category" in item?`<dt>Asset category</dt><dd>${sh(familyLabel((item as ScopeObject).asset_category))}</dd><dt>Disposition</dt><dd>${sh(familyLabel((item as ScopeObject).scope_disposition))}</dd><dt>Boundary relationship</dt><dd>${sh(familyLabel((item as ScopeObject).boundary_relationship))}</dd><dt>Implementation location</dt><dd>${sh(familyLabel((item as ScopeObject).implementation_location))}</dd><dt>Responsibility</dt><dd>${sh(familyLabel((item as ScopeObject).responsibility_model))}</dd>`:""}</dl><h3>Description</h3><p>${sh(item.description||("plain_language_summary" in item?String((item as unknown as {plain_language_summary:string}).plain_language_summary):"No additional description."))}</p><h3>Related records</h3>${related.length?`<div class="scope-related">${related.map(ref=>`<button data-scope-ref="${sh(ref)}">${sh(scopeRecordById(scope,ref)?.label??ref)}</button>`).join("")}</div>`:`<p class="muted">No visible related records.</p>`}<h3>Governing decisions</h3>${decisionRefs.length?`<div class="scope-related">${decisionRefs.map(ref=>`<button data-scope-ref="${sh(ref)}">${sh(scopeRecordById(scope,ref)?.label??ref)}</button>`).join("")}</div>`:`<p class="muted">No accepted Scope decision governs this record.</p>`}${profile!=="client"?`<h3>Provenance</h3><p>${sh(item.provenance.source_label)}</p><p class="meta">Origin: ${sh(familyLabel(item.provenance.origin_kind))} · asserted ${sh(item.provenance.asserted_at)}</p>`:""}</aside>`;
  }

  function bindScopeWorkspace(main:HTMLElement,store:ProjectStore):void {
    main.querySelectorAll<HTMLButtonElement>("[data-scope-tab]").forEach(button=>button.addEventListener("click",()=>{scopeTab=button.dataset.scopeTab as ScopeTab;selectedScopeRef="";renderScopeWorkspace(main,store);}));
    main.querySelectorAll<HTMLButtonElement>("[data-scope-ref]").forEach(button=>button.addEventListener("click",()=>{selectedScopeRef=button.dataset.scopeRef??"";renderScopeWorkspace(main,store);}));
    main.querySelector("#scope-close-inspector")?.addEventListener("click",()=>{selectedScopeRef="";renderScopeWorkspace(main,store);});
    main.querySelector("#scope-add-asset")?.addEventListener("click",()=>void addScopeAsset(store));
    main.querySelector("#scope-import")?.addEventListener("click",()=>ensureScopeInput().click());
    main.querySelector("#scope-generate-diagram")?.addEventListener("click",()=>generateScopeDiagram(store));
    main.querySelectorAll<HTMLButtonElement>("[data-scope-candidate]").forEach(button=>button.addEventListener("click",()=>decideCandidateUI(store,button.dataset.scopeCandidate??"",button.dataset.scopeCandidateAction as "accept"|"return"|"reject")));
    main.querySelectorAll<HTMLButtonElement>("[data-scope-accept-decision]").forEach(button=>button.addEventListener("click",()=>acceptDecisionUI(store,button.dataset.scopeAcceptDecision??"")));
    main.querySelectorAll<HTMLButtonElement>("[data-scope-return-decision]").forEach(button=>button.addEventListener("click",()=>returnDecisionUI(store,button.dataset.scopeReturnDecision??"")));
    main.querySelectorAll<HTMLButtonElement>("[data-scope-review-decision]").forEach(button=>button.addEventListener("click",()=>reviewDecisionUI(store,button.dataset.scopeReviewDecision??"",button.dataset.scopeReviewAction??"return")));
    main.querySelectorAll<HTMLButtonElement>("[data-scope-refresh-diagram]").forEach(button=>button.addEventListener("click",()=>refreshDiagramUI(store,button.dataset.scopeRefreshDiagram??"")));
    main.querySelectorAll<HTMLButtonElement>("[data-scope-review-diagram]").forEach(button=>button.addEventListener("click",()=>reviewDiagramUI(store,button.dataset.scopeReviewDiagram??"")));
    if(pendingScopeImport)main.insertAdjacentHTML("beforeend",renderScopeImportDialog(pendingScopeImport));
    bindScopeImportDialog(main,store);
  }

  async function addScopeAsset(store:ProjectStore):Promise<void> {
    const label=window.prompt("Synthetic asset label","New synthetic asset");if(!label)return;const kind=window.prompt("Asset kind","cloud-resource")||"other";
    store.execute("scope.asset.created","scope_asset",newId("scope-action"),"Created a draft Scope asset.",document=>{createScopeAsset(scopeDomain({document} as ProjectStore),{label,asset_kind:kind,visibility:"advisor-only",description:"Synthetic draft asset created for Scope review."},document.state.profile);});
  }
  function generateScopeDiagram(store:ProjectStore):void {store.execute("scope.diagram.generated","scope_diagram",newId("scope-action"),"Generated a deterministic draft Scope diagram without changing object authority.",document=>{const scope=scopeDomain({document} as ProjectStore);const ids=[...scope.boundaries,...scope.systems,...scope.assets,...scope.providers,...scope.services,...scope.data_flows].filter(item=>item.lifecycle!=="archived").slice(0,40).map(item=>item.id);if(!ids.length)throw new Error("No Scope records are available for a diagram.");scope.diagrams.push(createScopeDiagram(scope,`Scope diagram ${scope.diagrams.length+1}`,ids,document.state.profile));scope.updated_at=nowIso();scope.revision++;},"Generated Scope diagram draft");scopeTab="diagrams";}
  function decideCandidateUI(store:ProjectStore,id:string,action:"accept"|"return"|"reject"):void {const reason=window.prompt(`${familyLabel(action)} candidate rationale`,action==="accept"?"Accepted into Scope as a target-owned draft record.":`${familyLabel(action)}ed by Scope authority.`);if(!reason)return;store.execute(`scope.candidate.${action}`,"scope_candidate",id,`${familyLabel(action)}ed a Scope-owned candidate.`,document=>{decideScopeCandidate(scopeDomain({document} as ProjectStore),id,action,document.state.profile,reason);});}
  function acceptDecisionUI(store:ProjectStore,id:string):void {if(!window.confirm("Accept this exact-version Scope decision and atomically update only the named Scope-owned fields?"))return;store.execute("scope.decision.accepted","scope_decision",id,"Accepted an exact-version Scope decision.",document=>{acceptScopeDecision(scopeDomain({document} as ProjectStore),id,document.state.profile);},"Accepted Scope decision");}
  function returnDecisionUI(store:ProjectStore,id:string):void {const comment=window.prompt("Return comment","Clarify the source basis or affected exact version.");if(!comment)return;store.execute("scope.decision.returned","scope_decision",id,"Returned a Scope decision without changing governed object values.",document=>{const item=scopeDomain({document} as ProjectStore).decisions.find(decision=>decision.id===id);if(!item)throw new Error("Scope decision not found.");item.decision_state="returned";item.review_state="changes-requested";item.reviewer_comment=sanitizePlainText(comment,100000);item.version++;item.updated_at=nowIso();});}
  function reviewDecisionUI(store:ProjectStore,id:string,action:string):void {const comment=window.prompt("Reviewer comment",action==="concur"?"Concur with this proposed Scope decision.":"Return for Advisor changes.")??"";store.execute(`scope.decision.reviewer-${action}`,"scope_decision",id,`Reviewer ${action} disposition recorded.`,document=>{const item=scopeDomain({document} as ProjectStore).decisions.find(decision=>decision.id===id);if(!item)throw new Error("Scope decision not found.");item.reviewer_disposition=action==="concur"?"concur":action==="reject"?"reject":"return";item.reviewer_comment=sanitizePlainText(comment,100000);item.review_state=action==="concur"?"reviewed":action==="reject"?"rejected":"changes-requested";item.version++;item.updated_at=nowIso();});}
  function refreshDiagramUI(store:ProjectStore,id:string):void {store.execute("scope.diagram.refreshed","scope_diagram",id,"Refreshed a diagram to current exact Scope record versions.",document=>{const scope=scopeDomain({document} as ProjectStore),item=scope.diagrams.find(diagram=>diagram.id===id);if(!item)throw new Error("Scope diagram not found.");const map=scopeRecordMap(scope);item.included_record_refs=item.included_record_refs.map(ref=>({id:ref.id,version:map.get(ref.id)?.version??ref.version}));item.node_records=item.node_records.map(node=>node.record_ref?{...node,record_ref:{id:node.record_ref.id,version:map.get(node.record_ref.id)?.version??node.record_ref.version}}:node);item.currency_state="current";item.stale_ref_diagnostics=[];item.diagram_review_state="draft";item.approval_decision_ref=null;item.version++;item.updated_at=nowIso();});}
  function reviewDiagramUI(store:ProjectStore,id:string):void {store.execute("scope.diagram.reviewed","scope_diagram",id,"Marked a diagram reviewed as a representation; no object authority changed.",document=>{const item=scopeDomain({document} as ProjectStore).diagrams.find(diagram=>diagram.id===id);if(!item)throw new Error("Scope diagram not found.");item.diagram_review_state="reviewed";item.review_state="reviewed";item.version++;item.updated_at=nowIso();});}

  async function loadScopePackage(file:File):Promise<void { try{pendingScopeImport=await previewScopePackage(new Uint8Array(await file.arrayBuffer()),file.name);const main=document.getElementById("workspace");const hooks=scopeHooks();if(main&&hooks)renderScopeWorkspace(main,hooks.store);}catch(error){pendingScopeImport=null;window.alert(`Scope package preview failed: ${errorMessage(error)}`);} }
  function renderScopeImportDialog(preview:ScopeImportPreview):string {return `<dialog id="scope-import-dialog" class="scope-import-dialog" open><form method="dialog"><div class="scope-inspector-heading"><div><h2>Review Scope package</h2><p>${sh(preview.package_kind)} ${sh(preview.package_version)} · ${sh(preview.package_name)}</p></div><button value="cancel" aria-label="Close import preview">×</button></div><p class="mono">SHA-256 ${sh(preview.package_sha256)}</p><div class="scope-metrics"><div><strong>${preview.records.length}</strong><span>supported records</span></div><div><strong>${preview.rejected.length}</strong><span>rejected records</span></div><div><strong>${preview.warnings.length}</strong><span>warnings</span></div></div><div class="scope-import-records">${preview.records.map(item=>`<label><input type="checkbox" data-scope-import-record="${sh(item.import_record_id)}" ${item.selected?"checked":""}><span><strong>${sh(item.label)}</strong><small>${sh(familyLabel(item.family))} · ${sh(item.source_path)}</small></span><select data-scope-import-treatment="${sh(item.import_record_id)}"><option value="create" ${item.treatment==="create"?"selected":""}>Create candidate</option><option value="keep-separate" ${item.treatment==="keep-separate"?"selected":""}>Keep separate</option><option value="reject" ${item.treatment==="reject"?"selected":""}>Reject</option></select></label>`).join("")}</div>${preview.rejected.length||preview.warnings.length?`<div class="notice warning">${[...preview.warnings,...preview.rejected].map(item=>`<div>${sh(item)}</div>`).join("")}</div>`:""}<div class="dialog-actions"><button value="cancel">Cancel</button><button type="button" id="scope-reject-preview">Reject preview</button><button type="button" id="scope-apply-import" class="primary">Apply reviewed subset atomically</button></div></form></dialog>`;}
  function bindScopeImportDialog(main:HTMLElement,store:ProjectStore):void {const dialog=main.querySelector<HTMLDialogElement>("#scope-import-dialog");if(!dialog||!pendingScopeImport)return;dialog.addEventListener("close",()=>{pendingScopeImport=null;renderScopeWorkspace(main,store);});dialog.querySelectorAll<HTMLInputElement>("[data-scope-import-record]").forEach(input=>input.addEventListener("change",()=>{const item=pendingScopeImport?.records.find(record=>record.import_record_id===input.dataset.scopeImportRecord);if(item)item.selected=input.checked;}));dialog.querySelectorAll<HTMLSelectElement>("[data-scope-import-treatment]").forEach(select=>select.addEventListener("change",()=>{const item=pendingScopeImport?.records.find(record=>record.import_record_id===select.dataset.scopeImportTreatment);if(item)item.treatment=select.value as ScopeImportCandidate["treatment"];}));dialog.querySelector("#scope-reject-preview")?.addEventListener("click",()=>{pendingScopeImport=null;renderScopeWorkspace(main,store);});dialog.querySelector("#scope-apply-import")?.addEventListener("click",()=>{if(!pendingScopeImport)return;const preview=pendingScopeImport;store.execute("scope.import.applied","scope_import",preview.package_sha256,"Applied a reviewed Scope package subset atomically as low-authority candidates.",document=>{applyScopeImport(scopeDomain({document} as ProjectStore),preview,document.state.profile);},"Applied Scope compatibility package");pendingScopeImport=null;scopeTab="decisions";});}

  const observer=new MutationObserver(()=>queueScopeEnhance());
  const appRoot=document.getElementById("app");if(appRoot)observer.observe(appRoot,{childList:true,subtree:true});
  ensureScopeInput();queueScopeEnhance();
}
